### ISSUE TITLE
Serialization endpoint includeConceptDescriptions not working as expected

### ISSUE THREAD

**Issue by aaronzi** [eclipse-basyx/basyx-java-server-sdk#107]
When trying to download a serialized version of an AAS the ConceptDescription array is missing in the downloaded AAS when setting includeConceptDescriptions=true. Even when no ConceptDescription exists for the given AAS/Submodel, an empty array should be included. If it's not, the downloaded AAS can for example not be opened in the Package Explorer. 

For downloading JSON or XML files, it's not that big of an issue because the data can easily be completed (with `ConceptDescriptions: []` in the case of JSON for example).

When downloading .aasx files this is not possible. It would be nice to always include the ConceptDescription key when **includeConceptDescription** is set to true.

To reproduce the issue you can download any of the AASs in the example [here](https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/examples) through the AAS Environment. This would be an example get-request:
`http://localhost:1500/serialization?aasIds=aHR0cHM6Ly9hY3BsdC5vcmcvVGVzdF9Bc3NldEFkbWluaXN0cmF0aW9uU2hlbGw&submodelIds=aHR0cHM6Ly9hY3BsdC5vcmcvVGVzdF9TdWJtb2RlbA&includeConceptDescriptions=true`

**Comment by FrankSchnicke** [comment]
Is the array missing in case of CDs being referenced or only in the case of no CD being referenced?
Including the conceptDescriptions key if no CDs are included is a violation of the specification. The AASX Package Explorer not being able to open XML/AASX without this key is a bug, cf. https://github.com/admin-shell-io/aasx-package-explorer/issues/653

**Comment by aaronzi** [comment]
No, they are not missing if they exist as far as I can see.
I will close this issue then.
