### ISSUE TITLE
Endpoints for SubmodelElements inside Entities

### ISSUE THREAD

**Issue by aaronzi** [eclipse-basyx/basyx-java-server-sdk#108]
This is already part of the API specs and should also be included in BaSyx.
In this video, it is also showcased:

https://youtu.be/Szccn-EaH0Q?t=888

![image](https://github.com/eclipse-basyx/basyx-java-server-sdk/assets/17433117/3efde80e-55e7-4ab6-bd1c-f06c5faccf4d)

**Comment by FrankSchnicke** [comment]
Our implementation should already support this. Do you have an example where this is not the case?

**Comment by aaronzi** [comment]
That's nice to hear. Last time we talked you told me to open a feature request for this in the [aas-specs-api](https://github.com/admin-shell-io/aas-specs-api) repository. Therefore I thought it had not yet been implemented.

Anyway checked it with an example Entity and confirmed it. Thank you for the fast reply.

**Comment by FrankSchnicke** [comment]
When taking a look at figure you provided, I realized that I mixed something up - thanks for clarifing this!
