### ISSUE TITLE
Attachment Endpoints -> Submodel Repository

### ISSUE THREAD

**Issue by aaronzi** [eclipse-basyx/basyx-java-server-sdk#109]
Are those endpoints already implemented?

![image](https://github.com/eclipse-basyx/basyx-java-server-sdk/assets/17433117/64986d69-186a-4a25-9d86-70a2bf9463ad)

Will BaSyx V2 also have the option to store files internally (in the Submodel Repository respectively MongoDB?

**Comment by aaronzi** [comment]
In addition to that, it would also be nice to embed the defaultThumbnail of the asset-information inside the AAS Repository so that the Asset image can be retrieved via the API.

**Comment by FrankSchnicke** [comment]
> File Endpoints

The File endpoints are already implemented (cf. https://github.com/eclipse-basyx/basyx-java-server-sdk/pull/93).
The images on DockerHub will be updated end of next week, I will update this ticket here.

> defaultThumbnail 

The latest release of AAS4J is right now not supporting thumbnail retrieval from AASX. However, this will be supported in the next version of AAS4J and subsequently we will integrate the thumbnail endpoints into BaSyx.

**Comment by aaronzi** [comment]
Perfect, thanks for the info 👍🏻

**Comment by FrankSchnicke** [comment]
The images released yesterday include this feature
