### ISSUE TITLE
AASX Download not working

### ISSUE THREAD

**Issue by mm-mse** [eclipse-basyx/basyx-java-server-sdk#112]
With the newest container for the aas-environment on DockerHub the AASX-download is not working properly. The downloaded file can not be opened with the newest AASX package explorer. Also renaming the file from *.aasx to *.zip does not work in that sense that the zipped document cannot be accessed in windows file explorer.

**Comment by aaronzi** [comment]
This issue resulted from a bug in the AAS Web UI not fetching the binary AASX content as a blob. This is fixed here: https://github.com/eclipse-basyx/basyx-applications/pull/39
Now AASX files can be renamed to {filename}.zip and examined and also imported back to BaSyx V2 without any errors.

Nonetheless, AASX serialisations from aas4j cannot be opened in the Package Explorer. This is an issue with the Package Explorer, not aas4j or BaSyx.

**Comment by FrankSchnicke** [comment]
The AAS Web GUI was updated today, thus the blob issue should be fixed. For the general issues with AASX files with AAS4J and Package Explorer, cf. https://github.com/eclipse-aas4j/aas4j/issues/158
