### ISSUE TITLE
[Suggestion] Update Wiki for AAS Service configuration

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-basyx/basyx-java-server-sdk#114]
Hi,

for our project I have to set up some AAS Services and the documentation how to create the configuration/properties files is hard to understand. Today I had a look into the source code here and I saw that you use Spring Boot. Please mention this in your documentation. This will make your explanations easier, since many settings can be found in the official Spring Boot documentation. You can also hightlight which properties are important for the AAS. This will allow you to focus more on describing your own definitions.

KR,
BlackRose01

**Comment by FrankSchnicke** [comment]
Hi BlackRose01, 

thanks a lot for this suggestion. We added this point to our documentation:
https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/main/docs/Readme.md

Best regards,
Frank
