### ISSUE TITLE
[Suggestion] Merge configuration files to single file

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-basyx/basyx-java-server-sdk#115]
Hi,

please consider to merge your various configuration files (context.properties, security.properties, etc.) to a single file. Spring Boot allows to create custom namespaces in the application.(yml | properties). This makes it easier to have configurations created automatically and to build them up more logically. For example, links can be made within the file. Furthermore, the configuration file is read in automatically. Thus no own parsers and the like must be implemented.

Likewise, the rbac_rules.json can be mapped in the configuration file using a map. However, I would advise against this, as it becomes very confusing with many roles. Therefore, a file path and flag should be sufficient. Jackson can then read the file.

KR,
BlackRose01

**Comment by FrankSchnicke** [comment]
Hi,

thank you very much for this suggestion. For BaSyx V2, we're aiming at exactly doing this. Right now, there's only _application.properties_ for configurations and we are planning to include the _rbac_rules.json_ similar to how you described it. Feel free to take a look at the existing [examples ](https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/examples) for reference.

Best regards,
Frank
