### ISSUE TITLE
[Question] Does the new basyx version support environment variables instead of the properties files?

### ISSUE THREAD

**Issue by fcestari** [eclipse-basyx/basyx-java-server-sdk#123]
For instance, as documented in Basyx v1 [Environment Variables](https://wiki.eclipse.org/BaSyx_/_Documentation_/_Components_/_Environment_Variables#BaSyxMqttConfiguration.java)?

**Comment by aaronzi** [comment]
Yes, it does. You can use the exact same names as in the properties files but all capitalized and with "_" instead of "."

Here is an example for _basyx.environment_:
`BASYX_ENVIRONMENT`

**Comment by fcestari** [comment]
Thanks, @aaronzi.

**Comment by FrankSchnicke** [comment]
Thank you very much for pointing out this gap in the documentation. I added a section detailing the configuration via environment variables:
https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/main/docs/Readme.md#configuration-via-environment-variables
