### ISSUE TITLE
Provide endpoint to get metamodel version

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-basyx/basyx-java-server-sdk#136]
Hi,

it would be very nice to have an endpoint in the AAS Environment/AAS Registry REST API to monitor the version of the used meta model. With this information it would then be possible to integrate various AAS meta models in other systems. You can then use the version to decide which API version you need to use to obtain the necessary information. Currently it is not possible to see which AAS version is running.

KR,
BlackRose01

**Comment by FrankSchnicke** [comment]
Hi,

the new API version 3 defines a ["/description"](https://app.swaggerhub.com/apis/Plattform_i40/SubmodelRegistryServiceSpecification/V3.0.1_SSP-001#/Description%20API/GetDescription) endpoint that will provide this information. Thus, its absence implies that meta model Version 2 and the BaSyx API is used. If it is there, Metamodel & API Version 3 is used. It is already integrated in our components: https://github.com/eclipse-basyx/basyx-java-server-sdk/pull/94
