### ISSUE TITLE
Update base JDK image

### ISSUE THREAD

**Issue by mhrimaz** [eclipse-basyx/basyx-java-server-sdk#138]
Current JDK version is 11 however current LTS version is 21. Furthermore, an eclipse project using Amazon Corretto JDK. I guess it would be better to use Eclipse Temurin.

**Comment by alexgordtop** [comment]
eclipse-temurin images would be ok, too.

We usually use ubuntu based images, so something like "eclipse-temurin:21-jre-jammy"?

**Comment by FrankSchnicke** [comment]
We raised the used java version to java 17 in the meantime. Thus, I will close this issue.
