### ISSUE TITLE
Updating Resources From Environment File Not Possible

### ISSUE THREAD

**Issue by geso02** [eclipse-basyx/basyx-java-server-sdk#165]
When we upload aasx, json or xml files from the environment container, we can not update these resources again.

We need to restart the container - or start a new one - to upload the static file information again.

If the data is persisted in MongoDB, an exception is thrown in the "upload"-SpringBean on a new startup of the environment container.

We should handle exceptions and upload the updated resources when restarting the environment-container.

Possible approach:

- use the "administration" attribute with version and revision to indicate that the resource (shell, content-description, submodel) changed
- always override resources when no version or revision is assigned to the existing resource and the new resource
- if version or revision is set, update the resource only if at least one of the attributes changed

Nice to have:

Monitor file changes with spring integration and handle file changes to upload aasx resources

**Comment by FrankSchnicke** [comment]
Closed with linked PR.
