### ISSUE TITLE
Question: Property and Operation Delegation

### ISSUE THREAD

**Issue by wiresio** [eclipse-basyx/basyx-java-server-sdk#166]
I found a nice [feature](https://eclipse.dev/basyx/asset_integration/ ) using Property and Operation Delegations and implemented in [a setup for v1](https://github.com/eclipse-basyx/basyx-java-examples/tree/main/basyx.examples.deviceintegration/src/main/resources).

Question: Is this already working in v2?

**Comment by wiresio** [comment]
After having corrected my property to:
```
  {
      "idShort": "live",
      "qualifiers": [
          {
              "type": "delegatedTo",
              "valueType": "xs:string",
              "value": "http://localhost:8080/aidrunner/properties/count"
          }
      ],
      "valueType": "xs:integer",
      "value": "",
      "modelType": "Property"
  }

```
I get back an empty value. Maybe connection issues - will check.

**Comment by wiresio** [comment]
Connectivity tested via `docker exec -it CONTAINERID timeout 3 /bin/bash -c "echo > /dev/tcp/IPADDRESS/8080 >& /dev/null" && echo "ok" || echo "nok"` seems to be working - however, still no value. Any ideas?

**Comment by FrankSchnicke** [comment]
This is not implemented for V2 as of now. However, we will implement it in the coming weeks. 
I will keep this ticket open and update it whenever the feature is implemented.

**Comment by FrankSchnicke** [comment]
Operation Delegation is now implemented and will be included in the next release (i.e., next week).
Property Delegation, however, we're not planning to implement as of now. The reason is that it does not integrate well with the other architecture concepts of BaSyx (e.g., eventing). Since the value is only retrieved on-demand, features like eventing will not work as expected. I would advise for these scenarios to use the BaSyx DataBridge.

Do you have any scenario in mind where the DataBridge would not work but Property Delegation does?

**Comment by wiresio** [comment]
Thanks for the efforts and the update!

I think it is fine to use a gateway (e.g., DataBridge or [node-wot](https://github.com/eclipse-thingweb/node-wot)) to take care of the data collection and update of the respective Submodels or Submodel Elements. Eventing is anyhow preferred over cyclic polling.

Once the feature is pushed to main, it would be great if you could also provide a sample AAS to see both Operation Delegation as well as Eventing in action.

Another approach towards data collection in the AAS was recently prototyped in a [AASX Package Explorer branch](https://github.com/admin-shell-io/aasx-package-explorer/tree/MIHO/TMV30_SAMM_Xmas2023) via AID / AIMC Submodels. Maybe both approaches can be streamlined.

**Comment by FrankSchnicke** [comment]
> Once the feature is pushed to main, it would be great if you could also provide a sample AAS to see both Operation Delegation as well as Eventing in action.

We're planning on providing these examples. I will send an update on the basyx-dev mailing list whenever they are available.

> Another approach towards data collection in the AAS was recently prototyped in a [AASX Package Explorer branch](https://github.com/admin-shell-io/aasx-package-explorer/tree/MIHO/TMV30_SAMM_Xmas2023) via AID / AIMC Submodels. Maybe both approaches can be streamlined.

We would like to integrate AID / AIMC with the BaSyx DataBridge in a first step. Additionally, configurating operation delegation via these submodels is also a very interesting topic. However, for this there is no concrete ETA at the moment.
