### ISSUE TITLE
Endpoint "Serialization" seems not to work correctly

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-basyx/basyx-java-server-sdk#168]
Hello,

for a test I tried to use the Endpoint "Serialization" and I don't know how to interpret the output because I expected a readable XML file with all the information about the given AAS's and Submodels. I attached a screenshot from Swagger and the XML file.
Maybe a small suggestion for the endpoint. The content of the output could be depend on the requested content type, which is given by the request header. So when you send a get request with the content-type "application/json" then you will receive a response with a JSON body and the content-type "application/xml" returns a XML document.

KR,
BlackRose01

![Screenshot 2024-01-02 093922](https://github.com/eclipse-basyx/basyx-java-server-sdk/assets/7542316/4fad592d-63e7-4091-908d-b61bf4e8c202)

XML File (Could not upload XML file beccause Github does not allow that, so I renamed the file to .txt)
[response_1704184357304.xml.txt](https://github.com/eclipse-basyx/basyx-java-server-sdk/files/13808298/response_1704184357304.xml.txt)

**Comment by aaronzi** [comment]
As far as I can see in the curl field you are using `accept: application/asset-administration-shell-package+xml`. If you use this you will get an AAS package which is basically an AASX file. This is a binary file which you can see when looking at the symbols in the response body field. If you want an XML file you have to use `accept: application/xml`. This will give you a human-readable response.

Hope this helps :)

**Comment by FrankSchnicke** [comment]
> Maybe a small suggestion for the endpoint. The content of the output could be depend on the requested content type, which is given by the request header. So when you send a get request with the content-type "application/json" then you will receive a response with a JSON body and the content-type "application/xml" returns a XML document.

It is easy to miss in the Swagger documentation - but this is exactly what is being supported right now. If you take a look at the response documentation, you will see valid values for the accept header:

![image](https://github.com/eclipse-basyx/basyx-java-server-sdk/assets/77283144/832456c9-4bf4-4a69-8780-ec024b0ddcda)

**Comment by BlackRose01** [comment]
Ah. Ok. Thank you. I cannot change the Media Type in Swagger because I can only use the one predefined value. But when I try it with curl itself and change the media type to application/xml then I receive a valid XML document. With the predefined value and rename the output file to .aasx it won't work.

**Comment by FrankSchnicke** [comment]
What exactly do you mean with "won't work" - you can't open it in the AASX Package Explorer or something else?

**Comment by BlackRose01** [comment]
Correct. Sorry for the confusion. I cannot open the file in the aasx explorer when I use the Accept Header with the value `application/asset-administration-shell-package+xml`.

**Comment by FrankSchnicke** [comment]
This is related to a compatibility issue with AASX Package Explorer. For further details, see https://github.com/admin-shell-io/aasx-package-explorer/issues/654 and should be fixed whenever the maintainers of the package explorer merge my PR linked in the issue.

Since this is not related to the serialization endpoint itself, I will close this ticket.
