### ISSUE TITLE
Is Snapshot version functional?

### ISSUE THREAD

**Issue by wiresio** [eclipse-basyx/basyx-java-server-sdk#17]
Just tried to upload a submodel via the Swagger API and got a 400:
```
connection: close 
content-length: 0 
date: Tue,09 May 2023 13:35:38 GMT 
```
So, is the current Snapshot version really functional?

**Comment by FrankSchnicke** [comment]
I think the automatically generated Submodels of the SwaggerUI are somehow not correct. If you take a look at the example JSONs that we are using for testing (e.g., https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/main/basyx.submodelrepository/basyx.submodelrepository-http/src/test/resources/SingleSubmodel.json) you will find working examples
