### ISSUE TITLE
Question: MongoDB backend planned for Submodel Repository?

### ISSUE THREAD

**Issue by wiresio** [eclipse-basyx/basyx-java-server-sdk#19]
Is it planned to provide a connector for MongoDB serving as a backend for the Submodel Repository? Or is the idea to use the AAS Repository backend for this - which would mean that after each startup the In-Memory DB of the SM-Repo is synchronized?

**Comment by FrankSchnicke** [comment]
We will support MongoDB backend for the Submodel Repository in the coming weeks. I will update this ticket when the implementation is done.

**Comment by wiresio** [comment]
Another question (a bit related): I implemented a custom "feature-database" for the Submodel Repository. When I start the Submodel Repository standalone, the feature is invoked and can be used. However, when I start the Environment the feature is not recognized and thus not loaded. Same holds when I try with "feature-mqtt". I this a known issue or just a configuration problem?

**Comment by wiresio** [comment]
> Another question (a bit related): I implemented a custom "feature-database" for the Submodel Repository. When I start the Submodel Repository standalone, the feature is invoked and can be used. However, when I start the Environment the feature is not recognized and thus not loaded. Same holds when I try with "feature-mqtt". I this a known issue or just a configuration problem?

Working now - application.properties @ Environment defines the properties of all components.

**Comment by FrankSchnicke** [comment]
The mongodb backend for submodel repository is now integrated in the latest snapshot release on DockerHub as well as in the code in this repository.
