### ISSUE TITLE
Required RemoveSubmodelReference permission should be Update instead of Delete - AASRepo

### ISSUE THREAD

**Issue by geso02** [eclipse-basyx/basyx-java-server-sdk#198]
We need the permission UPDATE to add a submodelreference to a shell. It should be the same required action (Action.UPDATE) to remove the submodel reference from the shell again. 
```java

	@Override
	public void addSubmodelReference(String shellId, Reference submodelReference) {
		boolean isAuthorized = permissionResolver.hasPermission(Action.UPDATE, new AasTargetInformation(shellId));
		throwExceptionIfInsufficientPermission(isAuthorized);
		decorated.addSubmodelReference(shellId, submodelReference);
	}

	@Override
	public void removeSubmodelReference(String shellId, String submodelId) {
->		boolean isAuthorized = permissionResolver.hasPermission(Action.DELETE, new AasTargetInformation(shellId));
```

https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/main/basyx.aasrepository/basyx.aasrepository-feature-authorization/src/main/java/org/eclipse/digitaltwin/basyx/aasrepository/feature/authorization/AuthorizedAasRepository.java#L126

**Comment by mdanish98** [comment]
Hi @geso02 

Thanks for the suggestion, you are right, we also think this way. We will modify this and update the status here.

**Comment by mdanish98** [comment]
Hi @geso02,

The suggested improvement has been done with the attached PR.
