### ISSUE TITLE
Problem with updating docker image from 2.0.0-SNAPSHOT-NOINDEX to 2.0.0-SNAPSHOT for CosmosDb

### ISSUE THREAD

**Issue by pawel-baran-se** [eclipse-basyx/basyx-java-server-sdk#201]
We are running into problem when updating docker container for CosmosDb. 
In general if we were running on NOINDEX previously and after update of the image we got "Internal Server Error" while fetching data. 
Solution could be to clean the database and then create new data using updated image(without the NOINDEX) but this is impossible in our case. 
Please see bellow screenshot from logs:
![Screenshot 2024-02-02 152532](https://github.com/eclipse-basyx/basyx-java-server-sdk/assets/98280057/37c82a8f-71d6-43ac-9c6d-1b1c0d8c5dc5)

Thank you in advance for any hints or help

**Comment by FrankSchnicke** [comment]
Thanks a lot for pointing this out. We will take a look at this.

**Comment by pawel-baran-se** [comment]
Hello Frank,

Thank you for the update. 
Unfortunately, it would not be a solution for us. Do you see any other possible solution?
