### ISSUE TITLE
AAS-Environment crashes for special AAS-IDs

### ISSUE THREAD

**Issue by stolze-ifak** [eclipse-basyx/basyx-java-server-sdk#204]
I used the AAS environment component in different projects, so with different developers for the AAS files. 
The AAS environment of one of the projects crashes at starting. I saw a little difference in the AAS files. Some have as AAS ID something like "http://example..." and the others something like "www.example...". When I use the AAS files with "http://..." in the ID then the environment doesn't crash. When I use "www. .." then it crahses. I also noticed that this naming convention doesn't apply to the submodel ID. Here I can use both and the environment starts without errors. 

To reproduce the error I attached my code with both AAS files. In both files the submodel ID is the same (without "http://") :
[aas-env-setup.zip](https://github.com/eclipse-basyx/basyx-java-server-sdk/files/14165209/aas-env-setup.zip)

**Comment by FrankSchnicke** [comment]
The log points out

```
Duplicate element id detected with id www.example.com/ids/sm/1225_9020_5022_1974
```

By adding the "http://" you avoid the Id collision. Thus, the issue is the id duplication between two elements.

**Comment by stolze-ifak** [comment]
To obtain the error message, you must test both AAS files separately. If you test it together than you have a duplicated ID, thats correct.

**Comment by FrankSchnicke** [comment]
Thanks for pointing this out. However, I can't reproduce the issue. Can you post a log file?

**Comment by stolze-ifak** [comment]
Okay you are right. In my uploaded example AAS the error doesn't occur. Sorry for this. 

But I reproduced the error if I load the projects original AASX package with several AAS inside it again. After deleting some AAS in the package the environment doesn't crash. So it was the configuration of some AAS that wasn't correct. The example code above shows, that one can use both namings and it works.
