### ISSUE TITLE
Docker HealthCheck failing after enabling authorization

### ISSUE THREAD

**Issue by oalagtash** [eclipse-basyx/basyx-java-server-sdk#209]
After enabling authorization, images are marked as unhealthy due 401 (Authentication required):
<img width="798" alt="image" src="https://github.com/eclipse-basyx/basyx-java-server-sdk/assets/45067361/ecd0cb31-e9b4-4dfe-985c-a10832a1d0e1">

**Comment by FrankSchnicke** [comment]
Thank you very much for raising this issue. We will take a look and come back with a solution.

**Comment by FrankSchnicke** [comment]
This has been fixed with the linked PR and will be included in the next update of the components (latest next week)
