### ISSUE TITLE
Event Bus for Registry and Environment

### ISSUE THREAD

**Issue by BlackRose01** [eclipse-basyx/basyx-java-server-sdk#217]
Hi,

it would be very nice to have an event bus for registry and environment. This would be very useful to automate processes. Some events for the Registry could be AAS_REGISTERED (new AAS registered), ASS_UNREGISTERED (AAS disconnected or removed), AAS_UPDATED (e.g. AAS updates connection information) and for the environment AAS_STARTED (AAS ready to word), AAS_STOPPED (AAS is shutting down), AAS_UPDATED (add/remove model parts). This system should also avoid to poll the registry or AAS every time.

The process looks like the following:
When a new AAS registers with the registry, it should trigger an external service. The external service should then configure an EDC and obtain various information from other systems.

KR,
BlackRose01

**Comment by mdanish98** [comment]
Hi @BlackRose01 ,

I think your request is similar to the [MQTT Eventing feature](https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/basyx.aasrepository/basyx.aasrepository-feature-mqtt) in the repositories (AAS/SM Repo). 
And you want a similar feature for Registries. Is it correct?

**Comment by BlackRose01** [comment]
That is correct.

**Comment by mdanish98** [comment]
Thanks for your acknowledgement.

This is not on our immediate roadmap, but we will keep the ticket open and update it whenever this is being implemented.

**Comment by geso02** [comment]
Right now, this feature is implemented using Apache Kafka events for both registries and could be extended for other message brokers too. Here is the event implementation for Kafka and the related release project:

https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/main/basyx.submodelregistry/basyx.submodelregistry-service-kafka-events/src/main/java/org/eclipse/digitaltwin/basyx/submodelregistry/service/KafkaRegistryEventsConfiguration.java

https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/main/basyx.submodelregistry/basyx.submodelregistry-service-release-kafka-mem/src/main/docker/Dockerfile#L13

**Comment by aaronzi** [comment]
I am closing this as there have been no comments for 4 months and a solution already exists for the feature requested.
