### ISSUE TITLE
Graceful failure/conflict strategy on finding existing semantic IDs in MongoDB

### ISSUE THREAD

**Issue by abhishekmaha23** [eclipse-basyx/basyx-java-server-sdk#219]
While deploying the Basyx services, when semantic IDs are found already in the MongoDB database, the AAS environment, AAS registry and SM registry services fail non-gracefully. It would be useful to have a way to support either _overwrite_ or _reuse_ strategies for IDs already present in the database.

Currently my backup method is to clear and redeploy MongoDB entirely after removing PersistentVolumes in Kubernetes, and I'm only able to rapid-test with the in-memory images.

**Comment by mdanish98** [comment]
Hi @abhishekmaha23 ,

Thanks for pointing this out.
We will discuss this internally and come back to you.

**Comment by FrankSchnicke** [comment]
I think you are referencing a scenario where AAS, Submodels and ConceptDescriptions are preconfigured, right?
This is supported if you are using version & revision as documented here:
https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/basyx.aasenvironment#preconfiguration-of-aas-environments

Does this solve your issue?

**Comment by FrankSchnicke** [comment]
Closed due to inactivity. Feel free to comment if the issue is still relevant, I will gladly reopen the issue if required.
