### ISSUE TITLE
How to add an example file to 'test_demo_full_example.xml'

### ISSUE THREAD

**Issue by Jasar92** [eclipse-basyx/basyx-java-server-sdk#235]
Hi, 

I have used the docker-compose file given under [examples](https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/examples) to launch AAS UI. I would like to add an example pdf file to the .aasx file created using [test_demo_full_example.xml](https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/main/examples/aas/test_demo_full_example.xml).  

![image](https://github.com/eclipse-basyx/basyx-java-server-sdk/assets/43404543/a4c5acec-cf83-4dd2-9ede-534716829d57) 

When I try to download this example file I get an http 404 'not found error'. I cannot even upload a new file using 'upload file' option given in the UI.  Could you please help me add a file to this Test ASS environment.

**Comment by aaronzi** [comment]
Hi @Jasar92,

Thanks for submitting this issue. XML files cannot contain files themselves. You would need an .aasx file that has a file embedded in it. Since you started basyx with the XML file you showed in your screenshot, basyx can't include this file because it doesn't exist. The value only contains a path to a non-existing file and therefore you get this 404 error.

What you could do is open this in the AASX Package Explorer and add a file there. Then you can export your AAS as .aasx file. Uploading files through the basyx AAS Web UI would in general also be an option but I haven't updated the UI to support the new attachment endpoints for uploading yet. Only downloading is possible as of now. I will try to include this in the next update.

**Comment by Jasar92** [comment]
Great, thanks a lot. Yeah, uploading via a http (PUT) request will be really useful as I am looking to update the .aasx file without having to download and re-open via the package explorer.

**Comment by FrankSchnicke** [comment]
The submodel's unique id is the id that you have chosen for the Submodel where the File Submodel is residing. The idShortPath is either the idShort of the SubmodelElement if it is not contained in a SubmodelElementCollection & SubmodelElementList. If it is contained in either of those, you have to construct the idShortPath following the rules described in Part 2 of the specification (e.g., "sme.fileIdShort" or "sml[0].fileIdShort")

**Comment by Jasar92** [comment]
Thanks, I was able generate a request URL using the submodel unique ID, the PUT command execute without an error. However when I visit AAS UI I cannot visualise or download the correct file. This is how the page looks like after uploading the file.

![image](https://github.com/eclipse-basyx/basyx-java-server-sdk/assets/43404543/e07ed42b-6da4-499c-931a-bc6fe7c29d4c)

**Comment by FrankSchnicke** [comment]
What file did you upload? If I'm intepreting the screenshot correctly, did you upload a screenshot of the AAS UI itself? If yes, it is being visualized as expected on the right-hand side.

**Comment by Jasar92** [comment]
No I uploaded a different file [newfile.pdf](https://github.com/eclipse-basyx/basyx-java-server-sdk/files/14930904/newfile.pdf) even when I try to download the file it re-directs me to a new page of AAS UI. The following REST API was used to upload the file
```
http://localhost:8081/submodels/aHR0cDovL2FjcGx0Lm9yZy9TdWJtb2RlbHMvQXNzZXRzL1Rlc3RBc3NldC9Gb3JnaW5n/submodel-elements/ForgingDataCollection.ExampleFile/attachment?fileName=TestFile
```

**Comment by aaronzi** [comment]
I tried to reproduce what you were doing. I went to a file submodelElement that already had the MimeType application/pdf. Then I selected the file you attached to you comment and clicked on upload (see first screenshot). Afterwards it showed the PDF to the right in the Visualization window where I was also able to download the PDF from (see second screenshot). Are you doing the same? Can you provide more details if this does not help.  Also check which version of the UI you are using. Try the newest version just to make sure.

![image](https://github.com/eclipse-basyx/basyx-java-server-sdk/assets/17433117/98991e1e-3057-4cb3-b234-4738358e7475)

![image](https://github.com/eclipse-basyx/basyx-java-server-sdk/assets/17433117/1dbb0163-492f-4f56-bf10-a2d8b0bd4eb3)

**Comment by Jasar92** [comment]
It is working now ,thanks. I was using an old version of the UI.
