### ISSUE TITLE
Upload AAS endpoint CORS

### ISSUE THREAD

**Issue by aaronzi** [eclipse-basyx/basyx-java-server-sdk#238]
Uploading AAS files from a web frontend currently throws a CORS error. The endpoint is not affected by the CORS-related settings of the AAS Environment (as it seems).

**Comment by FrankSchnicke** [comment]
Thanks a lot for raising this issue. We will take a look and come back with a fix.

**Comment by mateusmolina-iese** [comment]
Hi @aaronzi,

thanks for letting us know. I'll investigate the issue and report back as soon as possible.

**Comment by mateusmolina-iese** [comment]
The CORS configuration for the upload endpoint was indeed missing. I quickly added it in #248. 

@FrankSchnicke, could you please take a look?

**Comment by FrankSchnicke** [comment]
Merged. The fix will be included in the updated components next week.

**Comment by aaronzi** [comment]
Thank you @mateusmolina-iese & @FrankSchnicke
