### ISSUE TITLE
424 Error when delegating an Operation

### ISSUE THREAD

**Issue by Aegid1** [eclipse-basyx/basyx-java-server-sdk#240]
When delegating an Operation from the AAS Environment to an Operation in the SubmodelService, a **424 Failed Dependency (WebDAV) (RFC 4918)** error occurs.
The qualifier is set correctly, because when delegating the Operation from the AAS Environment, it correctly connects to the SubmodelService.

**Comment by FrankSchnicke** [comment]
Error Code 424 is signalling that the HTTP/REST endpoint being delegated to is returning an error code. Can you provide more details about your setup and test if the endpoint delegated to is working as expected?

**Comment by Aegid1** [comment]
Sure!

The setup contains an **AAS-Environment** which contains the following Operation that delegates the Operation to the **SubmodelService**: ![image](https://github.com/eclipse-basyx/basyx-java-server-sdk/assets/107999252/e2cbe0d5-5b87-4c0d-973c-dd2cfcd61dec)


and the corresponding **SubmodelService** that contains the square operation which gets actually executed.
![SubmodelServiceScreenshot](https://github.com/eclipse-basyx/basyx-java-server-sdk/assets/107999252/d27d8f22-0363-4a5e-89a4-bd4bf64d30b1)

The square operation is the same as the one from the examples and works when invoked directly: 
![image](https://github.com/eclipse-basyx/basyx-java-server-sdk/assets/107999252/2b7ee05c-7240-47b9-bfa9-e1b5ad99ab2b)

I used host.docker.internal as the hostname because both components are launched locally via a docker-compose file. I tested the invocation via the **AAS-WebUI** and manually with **Postman**. In both cases i get the same error 424. 
When looking further into the logs of the docker container, there are no other loggings that indicate an error. 
The OperationDelegation feature is enabled and I use the most recent image of the **AAS-Environment**.
I also made sure that the **AAS-Environment** container can connect to the **SubmodelService** by directly sending the request inside the container:
![Screenshot](https://github.com/eclipse-basyx/basyx-java-server-sdk/assets/107999252/683ba1ed-d4ac-4045-8346-e5a9235215e3)

**Comment by FrankSchnicke** [comment]
Thank you very much for providing more details. This should work indeed - would it be possible to upload your complete setup (docker compose, AASX, project for the Submodel Service) to GitHub or share via other means with me?

Regardless of this issue, wouldn't it make more sense to move the complete Submodel contained in the Repository to a standalone SubmodelService or vice-versa, only implement the operation interface without the need for starting a complete SubmodelService?

**Comment by FrankSchnicke** [comment]
Is this issue still relevant?

**Comment by Aegid1** [comment]
I think it is not relevant anymore. Thanks for your suggestions :)
