### ISSUE TITLE
Superpath methods missing from the AAS Repository? 

### ISSUE THREAD

**Issue by DenisBiondic** [eclipse-basyx/basyx-java-server-sdk#241]
According to IDTA API Spec, only profile for the AAS Repository is the one specified with the Submodel Repository as the superpath, however this seems to be missing from the AAS Repository off-the-shelf component. 

Is this ommited on purpose, and if yes, can you shortly explain why?

![image](https://github.com/eclipse-basyx/basyx-java-server-sdk/assets/3341262/4296bc9f-8a5c-41c0-bd09-9e492c4b8440) 

![image](https://github.com/eclipse-basyx/basyx-java-server-sdk/assets/3341262/7f73556f-cc08-47d0-bb74-9401fb75924e)

If my understanding is correct, these methods cannot be ommited (according to spec I mean :) ), because the /description interface should return a list of profiles which the API supports - and there is no profile with AAS-Repository methods only without a superpath.

**Comment by FrankSchnicke** [comment]
Hi, I see from the linked issue that you already found the related issues that I've raised in the aas-api-sec group. I think it would be better to continue discussion there. If you agree, I will close this issue here.
