### ISSUE TITLE
Dependency Conflict with Spring Boot

### ISSUE THREAD

**Issue by gerberm-at-msg** [eclipse-basyx/basyx-java-server-sdk#260]
Hi @ all, 
I have the following issue. Can you please help me with it:

In my gradle file I include the following dependencies:

```
repository: 
...
maven {
        url "https://oss.sonatype.org/content/repositories/releases/"
    }
...
implementation 'org.eclipse.basyx:basyx.sdk:1.5.1'
implementation 'org.springframework.boot:spring-boot-starter:3.2.4' (current version)
implementation 'org.springframework.boot:spring-boot-starter-web:3.2.4' (current version)
```

my server is running starting without the basyx.sdk but will not start by just even referencing the basyx.sdk.

I receive the following error message:
```
**************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.configureContext(TomcatServletWebServerFactory.java:391)

The following method did not exist:

    'void org.apache.catalina.Context.addServletContainerInitializer(jakarta.servlet.ServletContainerInitializer, java.util.Set)'

The calling method's class, org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory, was loaded from the following location:

    jar:file:/.../.gradle/caches/modules-2/files-2.1/org.springframework.boot/spring-boot/3.2.4/ccb7cbb30dcf1d91dbbf20a3219a457eead46601/spring-boot-3.2.4.jar!/org/springframework/boot/web/embedded/tomcat/TomcatServletWebServerFactory.class

The called method's class, org.apache.catalina.Context, is available from the following locations:

    jar:file:/.../.gradle/caches/modules-2/files-2.1/org.apache.tomcat/tomcat-catalina/9.0.85/629375aad4a15202608a644baf50f7036d3d226d/tomcat-catalina-9.0.85.jar!/org/apache/catalina/Context.class
    jar:file:/.../.gradle/caches/modules-2/files-2.1/org.apache.tomcat.embed/tomcat-embed-core/10.1.19/3dbbca8acbd4dd6a137c3d6f934a2931512b42ce/tomcat-embed-core-10.1.19.jar!/org/apache/catalina/Context.class

The called method's class hierarchy was loaded from the following locations:

    org.apache.catalina.Context: file:/.../.gradle/caches/modules-2/files-2.1/org.apache.tomcat/tomcat-catalina/9.0.85/629375aad4a15202608a644baf50f7036d3d226d/tomcat-catalina-9.0.85.jar


Action:

Correct the classpath of your application so that it contains compatible versions of the classes org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory and org.apache.catalina.Context


Process finished with exit code 1
```

My System:
MacOS Sonoma 14.4
JavaSDK jbr-17 (JetBrains Runtime) - sourceCompatibility: 17.0.9
Gradle Version:  8.7

Do i use the correct dependencies? 
Which one should I use? 

My Software starts a Server that receives data via REST-API from a Sensor. I like to change now the code to integrate the AAS infrastructure. 

Thank you!

**Comment by FrankSchnicke** [comment]
Hi, 

is there any reason why you are using BaSyx V1 in contrast to BaSyx V2? You will find the milestone-02 parts on [Maven Central](https://central.sonatype.com/namespace/org.eclipse.digitaltwin.basyx).

**Comment by gerberm-at-msg** [comment]
Hi Frank, 
thank you for your response. Thats a valid point, that was no intention, thanks for mention it. It was the only link I was able to find. Can you provide the gradle configuration for the v2, I couldn't find it. Thank you!
Best 
Michael

**Comment by gerberm-at-msg** [comment]
Found it:
   implementation 'org.eclipse.digitaltwin.basyx:basyx.aasregistry:2.0.0-milestone-02'
    implementation 'org.eclipse.digitaltwin.basyx:basyx.aasdiscoveryservice:2.0.0-milestone-02'
    implementation 'org.eclipse.digitaltwin.basyx:basyx.aasenvironment:2.0.0-milestone-02'
    implementation 'org.eclipse.digitaltwin.basyx:basyx.submodelregistry:2.0.0-milestone-02'
    implementation 'org.eclipse.digitaltwin.basyx:basyx.submodelrepository:2.0.0-milestone-02'
    implementation 'org.eclipse.digitaltwin.basyx:basyx.submodelservice:2.0.0-milestone-02'
    
Didn't realise that they are under digitaltwin, then basyx and not only basyx anymore.
