### ISSUE TITLE
In submodel service, what's the purpose of `inputVariables` and `outputVariables` of the operation SME?

### ISSUE THREAD

**Issue by t-yoshioka-uh** [eclipse-basyx/basyx-java-server-sdk#263]
Just a question.

In submodel service example in this repository, the submodel's submodel element `squareOperation` has `inputVariables` and `outputVariables` explicitly defined.
https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/2.0.0-milestone-02/basyx.submodelservice/basyx.submodelservice.example/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/example/ExampleSubmodelFactory.java#L96-L97

However, even when we manipulate `inputVariables` and `outputVariables` (like changing `idShort` or `valueType`) or totally omit them, the API works as usual with the request below.

```bash
curl --location 'localhost:8081/submodel/submodel-elements/squareOperation/invoke' \
--header 'Content-Type: application/json' \
--data '{
    "inputArguments": [
        {
            "value": {
                "modelType": "Property",
                "value": "2"
            }
        }
    ]
}'
```

Then, why are they defined explicitly? Are they documentation for the API users?

**Comment by FrankSchnicke** [comment]
The configuration of Operations via input & output variables can be used for further validation before executing the operation. However, BaSyx does not perform this validation at the moment. In future, this might be added.

**Comment by t-yoshioka-uh** [comment]
Thank you. I appreciate your information.
