### ISSUE TITLE
Submodel service cannot create and update submodel elements

### ISSUE THREAD

**Issue by t-yoshioka-uh** [eclipse-basyx/basyx-java-server-sdk#264]
# Overview

In submodel service implementation  as of tag `2.0.0-milestone-02`, an internal server error occurs when creating a submodel element. This is because the example implementation uses a fixed-size list returned by `Arrays.asList()`.
https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/main/basyx.submodelservice/basyx.submodelservice.example/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/example/ExampleSubmodelFactory.java#L77

Replacing the line above with `List<SubmodelElement> smeList = new ArrayList<>(Arrays.asList(sme1, square));` solves the problem of creation.

However, even after solving the problem, we cannot update the submodel element. It responds with 404 Not Found and after the request, the submodel element "mySME" disappears. The server logs nothing about the problem.

# Steps to reproduce

1. Checkout `2.0.0-milestone-02` of this repository
2. Replace ExampleSubmodelFactory.java#L77 as explained above
3. Run the example implementation of submodel service (org.eclipse.digitaltwin.basyx.submodelservice.example.ExampleSubmodelComponent)
4. Create a submodel element like below
5. Try to update the submodel element like below

<details>
<summary>Create a submodel element</summary>

```bash
curl --location 'localhost:8081/submodel/submodel-elements' \
--header 'Content-Type: application/json' \
--data '{
    "modelType": "Property",
    "value": "999",
    "idShort": "mySME"
}'
```

</details>

<details>
<summary>Try to update the submodel element</summary>

```bash
curl --location --request PUT 'localhost:8081/submodel/submodel-elements/mySME' \
--header 'Content-Type: application/json' \
--data '{
    "modelType": "Property",
    "value": "888",
    "idShort": "mySME"
}'
```

</details>

**Comment by FrankSchnicke** [comment]
Thanks a lot for providing this information. Would you be interested in raising a PR that fixes this issue?

The issue with PUT is already reported in https://github.com/eclipse-basyx/basyx-java-server-sdk/issues/246 and will be fixed soon.

**Comment by t-yoshioka-uh** [comment]
@FrankSchnicke 
Thank you for providing information on #246. I understand the situation.

Regarding the problem of creating/deleting submodel elements, I've created PR #267. Could you please review it?

By the way, the PR workflow fails perhaps because my GitHub account is not authorized. Do I have to do something to make it pass?

**Comment by FrankSchnicke** [comment]
> By the way, the PR workflow fails perhaps because my GitHub account is not authorized by your organization. Do I have to do something to make it pass?

I answered this point in the PR itself but to ensure that it is not getting lost:
Would it be possible to sign the Eclipse Contributor Agreement in your Eclipse account and link it with your GitHub account? I will gladly merge your contribution then.
