### ISSUE TITLE
AASX file cannot be uploaded again after deleting the AASs and Submodels

### ISSUE THREAD

**Issue by morhof123** [eclipse-basyx/basyx-java-server-sdk#269]
## Problem
When uploading a AASX file and then deleting all submodels / AASs that are contained in the file, BaSyx returns a 409 Conflict error when reuploading the AASX file.

## Steps to reproduce
- Adding an AAS through the "/upload" endpoint as AASX file which includes files (e.g. Thumbnails or Handover Documentation PDFs)
- Delete the Submodels, the Submodel-Refs from the AAS and the AASs that were included in the aasx file using the BaSyx API
- Try to upload the same AASX file again using the /upload endpoint => 409 Conflict

I believe that I am using this docker image:
`eclipsebasyx/aas-environment        2.0.0-SNAPSHOT       a5e33a832d08`

It looks like somehow the files won't get deleted thus hindering a reupload.

## Quick fix
Change the AAS-Id, Asset-Id and Submodel-Ids in the AASX file and then reupload

**Comment by morhof123** [comment]
I just tried it with an AAS without a file and it had the same error, maybe the problems aren't the files but the deletion

**Comment by FrankSchnicke** [comment]
Thanks for pointing this out. We will take a look at this and come back with a fix.

**Comment by FrankSchnicke** [comment]
The fix will be included in the update next week.
