### ISSUE TITLE
GUI "Error while parsing the Submodel References!"

### ISSUE THREAD

**Issue by brkycm** [eclipse-basyx/basyx-java-server-sdk#274]
Hello,

I am trying to upload a simple AAS file. I started the [aasx-server](https://github.com/eclipse-aaspe/aasx-server) and connected it to the aasx package explorer. Then I upload my aasx via the aasx package explorer. Finally, I add the aasx via the GUI with the AAS endpoint. I use the Docker image from the examples for the basyx infrastructure.

I did the same with the example V3 aasx from this github project and everything works fine. I don't understand the problem with my submodel reference. I also tried to change everything to match the sample AAS. Still I get the same error.

I am providing you my test aas.

Thank you very much in advance.
[test.zip](https://github.com/eclipse-basyx/basyx-java-server-sdk/files/15149370/test.zip)

**Comment by FrankSchnicke** [comment]
If I understand you correctly, you try to connect the AAS Web GUI to the AASX Server, right?

**Comment by brkycm** [comment]
Yes, that is correct.

My actual goal is to build the simplest possible infrastructure to upload an AAS as an .aasx file. Unfortunately, I don't understand exactly how all the new components of V2 are connected. I need the AASX server to upload my AAS there first, right? I then want to connect the AASX server to the other components via the GUI so that I can also use the AAS registry, for example. Most of the tutorials are for V1, so I'm having a bit of a hard time at the moment.

Thank you very much!

**Comment by aaronzi** [comment]
You could try out the starter kit for BaSyx. It's an interactive documentation. You can find it here:

https://basyx.org

There you are able to create a minimal config with the necessary repositories and registries as well as the GUI. The screenshot below shows the components to the right (the AAS Server is what we call AAS Environment). To the left I marked the relevant topics that you should take a look at. Hope this helps.

![image](https://github.com/eclipse-basyx/basyx-java-server-sdk/assets/17433117/6a00633e-a75d-4412-bbaa-8723679fa571)

**Comment by FrankSchnicke** [comment]
Additionally, you can take a look at the [example](https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/examples). There, it is illustrated how we load an AASX into BaSyx.

**Comment by seicke** [comment]
@FrankSchnicke Adding the wiki link (http://basyx-wiki.readthedocs.io/) to the [Readme.md](https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/main/README.md) would indeed be useful/helpful

@aaronzi Adding the starter kit link (https://basyx.org/#/get-started/introduction) would also be useful/helpful
