### ISSUE TITLE
Improvements on BaSyx delegation feature

### ISSUE THREAD

**Issue by mm-mse** [eclipse-basyx/basyx-java-server-sdk#286]
The feature of property or operation delegation offers great possibilities to retrieve data on demand or invoke operation via delegation. However there are two main issues that I would like to improve:

1. Defining a delegation happens via a qualifier named `invocationDelegation` or `propertyDelegation`. This qualifier contains the URL of the resource called for delegation. My problem is that this qualifier is not removed from the submodel after the data was retrieved. Returning the submodel with the included qualifiers leaks this URL and therefore information about my internal systems. This is neither necessary nor desirable for e.g. security reasons.

2. As I understand it for every property delegated there will be one HTTP call to the delegation endpoint. However there might be one endpoint providing multiple different properties for one requested submodel which means that there will happen a lot of traffic. Therefore I would like to have a mechanism that batches all delegations to one endpoint together into one request instead of n requests. This would reduce unnecessary traffic and might improve response times as well.

**Comment by mdanish98** [comment]
Hi @mm-mse ,

Thanks for your valuable suggestions.

Following are our remarks:
1. In the production environment, the access can be restricted using the [RBAC authorization](https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/basyx.submodelrepository/basyx.submodelrepository-feature-authorization) supported by BaSyx, hence only authorized users can access the Submodel with delegations. Doing this would solve the security concerns.
2. In BaSyx V1 property delegation was designed to just delegate the request to a single HTTP endpoint which provides a single data point as a response acceptable to the property, so no multiple data points. The input and output were already restricted. However, there is no plan now to implement the Property Delegation in BaSyx V2, the reasons are explained [here](https://github.com/eclipse-basyx/basyx-java-server-sdk/issues/166#issuecomment-1934715786). 

Please let me know if you have any remarks on this or if I misunderstood something.
