### ISSUE TITLE
Incosistent naming of Enums in openAPI-spec and returned bodies

### ISSUE THREAD

**Issue by SebBehrendt** [eclipse-basyx/basyx-java-server-sdk#296]
Hello, 

when using the official docker image of the aas-environment (dockerhub: eclipsebasyx/aas-environment:2.0.0-milestone-02), there seems to be an inconsistency of naming of Enums in returned requests and the openAPI specification of the aas-environment. 

E.g. the AssetKind (https://github.com/eclipse-aas4j/aas4j/blob/main/model/src/main/java/org/eclipse/digitaltwin/aas4j/v3/model/AssetKind.java):
- naming in openAPI spec and aas4j definition: "INSTANCE", "NOT_APPLICABLE", "TYPE"
- naming of AssetKind in returned GET requests to the aas-environment docker image: "Instance"

This error is present for all types of Enums in the aas-environemnt, as far as I know. Generated clients from the openAPI spec need to be manually adjusted to work. It would be great if the returned JSON are consistent with the openAPI spec of the server by adjusting the Enums. 

Thank you!

**Comment by mdanish98** [comment]
Hi @SebBehrendt 

Thanks for raising this issue.
We will check and get back to you.

**Comment by FrankSchnicke** [comment]
When using the JSON serialization of AAS4J, it is internally mapped to CamelCase (cf. [here](https://github.com/eclipse-aas4j/aas4j/blob/main/dataformat-core/src/main/java/org/eclipse/digitaltwin/aas4j/v3/dataformat/core/internal/serialization/EnumSerializer.java)) which is consistent with the specification (cf. Specification of the Asset Administration Shell Part 2, p. 168).

Are you using the official SwaggerHub specifications (e.g., [here](https://app.swaggerhub.com/apis/Plattform_i40/SubmodelServiceSpecification/V3.0.1_SSP-001)) for code generation?

**Comment by FrankSchnicke** [comment]
Yes, this might be an issue in the OpenAPI specification. There's an official repo of IDTA for that: 
https://github.com/admin-shell-io/aas-specs-api

Feel free to raise an issue there.

**Comment by arteeh** [comment]
> In the official documentation, the Enum Values of KeyTypes are also fully capitalized (https://app.swaggerhub.com/domains/Plattform_i40/Part1-MetaModel-Schemas/V3.0.1#/components/schemas/ReferenceTypes, line 535ff). I think this is probably the reason for the capitalized values...

I don't see capitalized values on line 535. Has this been fixed on the IDTA end? I couldn't find any related issues or PRs in https://github.com/admin-shell-io/aas-specs-api.

If this has been fixed, I assume this will end up in BaSyx in a future snapshot / release?

**Comment by SebBehrendt** [comment]
Hello,

you are correct. In the official documentation (e.g. in line 535), the enum values are correctly specified as camel case values. I think the only problem is, that the java server sdk specifies in its openAPI specification that enum values are fully capitalized (which is inconsistent with the actual API).
