### ISSUE TITLE
No MQTT Events send when changing MLPs

### ISSUE THREAD

**Issue by de-ich** [eclipse-basyx/basyx-java-server-sdk#299]
Hello,

I was testing the MQTT event feature of the submodel repository. MQTT events for changed "Property" elements work just fine. However, changing values of "MultiLanguageProperty" elements (or adding/removing of languages) do not seem to lead to an MQTT event.

I used the following setup:
- eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
- eclipsebasyx/aas-gui:v2-240515

Best regards
Matthias

**Comment by mdanish98** [comment]
Hi @de-ich ,

Thanks for raising this issue.

Would it be possible for you to share the configurations you used in this? like application.properties etc

**Comment by de-ich** [comment]
Sure. I use the following configuration files (note that I needed to add 'txt' file ending due to upload limitations of Github):

[docker-compose.yml.txt](https://github.com/eclipse-basyx/basyx-java-server-sdk/files/15480762/docker-compose.yml.txt)
[aas-env.properties.txt](https://github.com/eclipse-basyx/basyx-java-server-sdk/files/15480765/aas-env.properties.txt)
[aas-registry.yml.txt](https://github.com/eclipse-basyx/basyx-java-server-sdk/files/15480771/aas-registry.yml.txt)
[sm-registry.yml.txt](https://github.com/eclipse-basyx/basyx-java-server-sdk/files/15480773/sm-registry.yml.txt)
[mosquitto.conf.txt](https://github.com/eclipse-basyx/basyx-java-server-sdk/files/15480795/mosquitto.conf.txt)

**Comment by aaronzi** [comment]
Some additional info:

There was a bug when updating SubmodelElements (including MLPs). This bug has just been fixed as part of this PR: #280
I think this fix is not in the latest version of the snapshot images. Therefore the BaSyx backend components do not support updating MLPs yet.

**Comment by aaronzi** [comment]
Update: Since updating an MLP currently uses PUT-Requests this issue is the same as #300.
Therefore please take a look at the latest comment there.

**Comment by aaronzi** [comment]
As this problem should have be resolved now in this PR #327 I will close this issue.
