### ISSUE TITLE
Dependency to license-tool-plugin:1.1.1-SNAPSHOT makes it hard to build out-of-the-box

### ISSUE THREAD

**Issue by in-fke** [eclipse-basyx/basyx-java-server-sdk#329]
Is it necessary to depend on the Snapshot version?
```
					<groupId>org.eclipse.dash</groupId>
					<artifactId>license-tool-plugin</artifactId>
					<version>1.1.1-SNAPSHOT</version>

```
makes it hard to build out-of-the-box, or pom.xml should specify the snapshot repository where it could be found.

`[ERROR] Plugin org.eclipse.dash:license-tool-plugin:1.1.1-SNAPSHOT or one of its dependencies could not be resolved: org.eclipse.dash:license-tool-plugin:jar:1.1.1-SNAPSHOT was not found in <URL> during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of <Repo-ID> has elapsed or updates are forced -> [Help 1]
`
besides, if you are planning to release, you should not depend on any other SNAPSHOT versions.

**Comment by in-fke** [comment]
Related: https://github.com/eclipse-basyx/basyx-java-server-sdk/pull/227

**Comment by in-fke** [comment]
Just found out I can comment it out completely, and build still works. 

```
			<!--
				<plugin>
					<groupId>org.eclipse.dash</groupId>
					<artifactId>license-tool-plugin</artifactId>
					<version>1.1.1-SNAPSHOT</version>
					<executions>
						<execution>
							<id>license-check</id>
							<goals>
								<goal>license-check</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
			-->
```

And I just found that `<pluginRepository>` is there, but it does not get picked up for some reason.
Probably a problem from my part, having `<mirror>` declarations in the Maven settings.xml.

```
	<pluginRepositories>
		<pluginRepository>
			<id>dash-licenses-snapshots</id>
			<url>https://repo.eclipse.org/content/repositories/dash-licenses-snapshots/</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>
```

**Comment by in-fke** [comment]
ok, my settings.xml needed something like

`<mirrorOf>*,!dash-licenses-snapshots</mirrorOf>`

question remains: do you want / need to rely on the SNAPSHOT version?

**Comment by FriedJannik** [comment]
Hi @in-fke,
Thanks for bringing this up.
You're right that we could switch to the release version of this plugin.
The project builds without this plugin as it is not a code dependency.
We will discuss this internally and adjust if necessary.

Since the build issue seems to be a problem on your end, and the build works fine for us and the CI, I think the issue would be resolved, right?

**Comment by in-fke** [comment]
> Since the build issue seems to be a problem on your end, and the build works fine for us and the CI, I think the issue would be resolved, right?

Ok, resolving this as is - if you want to take the use of "1.1.1-SNAPSHOT" itself on another level

**Comment by in-fke** [comment]
Actually I followed up into another problem, a transitive dependency of `license-tool-plugin`

`[ERROR] Failed to execute goal org.eclipse.dash:license-tool-plugin:1.1.1-SNAPSHOT:license-check (license-check) on project basyx.parent: Execution license-check of goal org.eclipse.dash:license-tool-plugin:1.1.1-SNAPSHOT:license-check failed: Plugin org.eclipse.dash:license-tool-plugin:1.1.1-SNAPSHOT or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.eclipse.dash:eclipse-api-for-java:jar:1.0.0 (absent): Could not find artifact org.eclipse.dash:eclipse-api-for-java:jar:1.0.0 in <mirror-repo> -> [Help 1]`

Artifact is here, but I did not manage to pull it from there.
https://repo.eclipse.org/content/groups/releases/org/eclipse/dash/eclipse-api-for-java/1.0.0/

tried the following:
```
		<repository>
			<id>repo.eclipse.org</id>
			<name>Eclipse Releases Repository</name>
			<layout>default</layout>
			<url>https://repo.eclipse.org/content/groups/releases/</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
```
