### ISSUE TITLE
Microsoft Entra AD Support

### ISSUE THREAD

**Issue by rosseboe** [eclipse-basyx/basyx-java-server-sdk#341]
Our company is using[ Microsoft Entra AD](https://www.microsoft.com/en-us/security/business/identity-access/microsoft-entra-id) as our identity provider.  
Before we are able to store actual company data in BaSyx, proper RBAC needs to be in place. 

To ease introduction and integration of BaSyx RBAC into our company, native support for Microsoft Entra AD would be really helpful.  

Alternatively, as a plan B, a how-to guide on setting up Basyx-Keycloak-EntraAD could also be useful to get us started.

**Comment by aaronzi** [comment]
We have decided not to implement this as a core feature of BaSyx Java V2 for the time being. You can have a look at our BaSyx example with Keycloak if you are interested in securing your BaSyx setup: https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/examples/BaSyxSecured

If this feature is important to you, please contact us directly. You can reach me at my mail: aaron.zielstorff@iese.fraunhofer.de
