### ISSUE TITLE
[BUG] Wrong HTTP-Statuscode On Thumbnail Upload

### ISSUE THREAD

**Issue by geso02** [eclipse-basyx/basyx-java-server-sdk#359]
When uploading a thumbnail, the return value should be a 204 (No Content) status code. However, a 200 (OK) status code is being returned

See: 

https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/main/basyx.aasrepository/basyx.aasrepository-http/src/main/java/org/eclipse/digitaltwin/basyx/aasrepository/http/AasRepositoryApiHTTPController.java#L202

**Comment by aaronzi** [comment]
Hi Gerhard, good find! If possible, please open a PR with a fix for this :)
