### ISSUE TITLE
[BUG] same Submodel Reference can be applied to same AAS again without throwing 409 (already exists)

### ISSUE THREAD

**Issue by merlinseela** [eclipse-basyx/basyx-java-server-sdk#373]
**Describe the bug**
I am creating a new Submodel Reference using the POST /shells/{aasIdentifier}/submodel-refs endpoint and executing it multiple times, the submodel Reference gets added successfully (201 created) and if i execute again it returns again a 201. 

From my perspective it does not make sense to "re-create" an already exisiting Reference. I would expect to get a 409 (already exisits) here.

**To Reproduce**
1. Open [Postman](https://www.postman.com/) and create a new POST Request and enter `{{aas_environment}}/shells/:aas_id_base64/submodel-refs` 
- for aas_environment set the adress of the aas environment e.g. localhost:8081
- for aas_id_base64 set a base-64 utf-8 encoded aas id
- enter the request body and replace with a known submodel from your environment

```
{
     "type": "MODEL_REFERENCE",
     "keys": [
         {
             "value": "<<none_base_64_encoded_submodel_id_to_reference_to>>",
             "type": "Submodel"
         }
     ]
}
```
2. Send the request. (This should come back with a 201 (Created) Response)
3. Wait a bit.
4. Send the request again.
5. It should return again a 201.

**Expected behavior**
By already existing Reference / trying to recreate the same reference it should throw a 409 (already exists.)

**BaSyx:**
- BaSyx Version v2.0 Snapshot (also made sure to update/redownload my images before posting)
- BaSyx SDK Java
- AAS Version DotAAS V3

**Screenshots**
![image](https://github.com/user-attachments/assets/669037ac-204e-48c4-b8f4-274f3f19d6f0)
![image](https://github.com/user-attachments/assets/d065907d-c664-4dab-815c-268c6c25ae21)

**Used Asset Administration files (.aasx/.json/.xml)**
I believe this error can be reproduced in any running aas environment with at least 1 submodel and 1 aas, even if the submodel is already referenced to the aas. 

**BaSyx configuration**
I do not think this is necessary if needed i will present it.

**System (please complete the following information):**
 - OS: Windows [Host] - AAS Off the Shelf Components [Docker]

**Additional context**
If there are any suggestions for this issue, especially how I presented the content of this issue, feel free to let know.

**Comment by mdanish98** [comment]
Hi @merlinseela 

Thanks for raising this issue.
We will analyze this issue and get back to you soon.

If we need further information, I'll let you know.
