### ISSUE TITLE
[BUG] Strange bug with Submodel Repository POST API when enabling MQTT eventing

### ISSUE THREAD

**Issue by de-ich** [eclipse-basyx/basyx-java-server-sdk#389]
**Describe the bug**
I wanted to verify that the fix for [283 - posting new SME into existing SMC](https://github.com/eclipse-basyx/basyx-java-server-sdk/issues/283) works for me when I noticed some strange behaviour: Under some constellations, the fix seemed to work, while under other constellations, it did not.

After some tests, I noticed that posting a new SME into an existing SMC works fine unless MQTT is configured in the properties file for the AAS env (which should be totally irrelevant).

Attached, I have provided an MWE that illustrates the bug.

**To Reproduce**

1. Download the Zip file [basyx-post-prop-bug.zip](https://github.com/user-attachments/files/16522390/basyx-post-prop-bug.zip) that contains a docker-compose project with a minimal Basyx setup
2. docker-compose up
3. Execute the file `test.bat` that is also contained in the zip file. This uses curl to create and populate an AAS (it actually performs the five steps described [here](https://github.com/eclipse-basyx/basyx-java-server-sdk/issues/283#issuecomment-2115601187))
5. Open the [BaSyx UI](http://localhost:3000/?aas=http://localhost:8086/shells/dGVzdEFhc0lk) and notice that the Property is created correctly as child of the SMC:
![image](https://github.com/user-attachments/assets/aec8c18f-60e4-4b5b-9f4f-8cd976142360)
7. Stop the docker containers
8. Within the file `basyx/aas-env.properties`, uncomment lines 11-15 (which will enable MQTT eventing for the aas-env)
![image](https://github.com/user-attachments/assets/78288fbc-2187-417c-b454-5e73cdc9a3cc)
9. Restart the docker containers
10. Once again run the batch script to create and populate the AAS
11. Open the [BaSyx UI](http://localhost:3000/?aas=http://localhost:8086/shells/dGVzdEFhc0lk) again and notice that the Property is now created as a direct child of the submodel instead of as child of the SMC.
![image](https://github.com/user-attachments/assets/d0487e7b-8002-4788-91f0-ab8ad302eb9f)

**Expected behavior**
The property should be created as child of the SMC independent of whether MQTT eventing is enabled or not.

**BaSyx (please complete the following information):**
- BaSyx Docker components V2.0.0-milestone-03.1

**BaSyx configuration**
See attached Zip file containing a complete docker-compose configuration

**System (please complete the following information):**
 - OS: Windows

**Comment by mdanish98** [comment]
Hi @de-ich ,

Thanks for raising this issue, we are analyzing this issue.
We'll update you once the analysis in done.
