### ISSUE TITLE
[BUG] No 409 Conflict Returned On Posting Sub Model Reference Again (AAS REPO)

### ISSUE THREAD

**Issue by geso02** [eclipse-basyx/basyx-java-server-sdk#394]
**Describe the bug**

In [this method](https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/main/basyx.aasservice/basyx.aasservice-backend-inmemory/src/main/java/org/eclipse/digitaltwin/basyx/aasservice/backend/InMemoryAasService.java#L96), no 409 conflict is returned (or an exception thrown) when adding a submodel reference if the reference already exists. However, the [OpenAPI description](https://app.swaggerhub.com/apis/Plattform_i40/AssetAdministrationShellRepositoryServiceSpecification/V3.0.2_SSP-001#/Asset%20Administration%20Shell%20Repository%20API/PostSubmodelReference_AasRepository) specifies this error code. When removing, only the first occurrence of the reference is removed. So if the reference is added multiple times, we should probably remove all references. 

Based on the OpenAPI description, I would assume that multiple references are not intended to be allowed, as the status code 409 suggests that duplicate entries should not be permitted.

**To Reproduce**
- Deploy the reference multiple times
- Get the shell and check for the submodels.

**Expected behavior**
- In my opinion, the expected behavior would be to return 409

**BaSyx (please complete the following information):**
- BaSyx Version [v2.0]
- BaSyx SDK [Java]
- AAS Version [DotAAS V3]

**Screenshots**

**Used Asset Administration files (.aasx/.json/.xml)**

Shell:
``` json 
       {
                "modelType": "AssetAdministrationShell",
                "assetInformation": {
                    "assetKind": "Instance",
                    "globalAssetId": "https://acplt.org/Test_Asset"
                },
                "submodels": [
                    {
                        "keys": [
                            {
                                "type": "Submodel",
                                "value": "http://acplt.org/Submodels/Assets/TestAsset/BillOfMaterial"
                            }
                        ],
                        "type": "ExternalReference"
                    }
                ],
                "id": "https://acplt.org/Test_AssetAdministrationShell",
                "idShort": "TestAssetAdministrationShell"
            }
```
Additional submodel reference (already existing):
``` json
                 {
                        "keys": [
                            {
                                "type": "Submodel",
                                "value": "http://acplt.org/Submodels/Assets/TestAsset/BillOfMaterial"
                            }
                        ],
                        "type": "ExternalReference"
                    }
```

**System (please complete the following information):**
 - OS: Docker(Windows)
 - CPU architecture:  x86

**Comment by aaronzi** [comment]
Hi @geso02, thank you for reporting this. Same Bug was already found in #373 and get's fixed with #388.
