### ISSUE TITLE
Any working example .aasx file?

### ISSUE THREAD

**Issue by emareg** [eclipse-basyx/basyx-java-server-sdk#402]
I have set up all docker containers according to the [Quick Start Guide](https://wiki.basyx.org/en/latest/content/introduction/quickstart.html) and they seem to work (containers run, UI reachable). 

The final step mentioned here is to upload a shell file. However, I do not have one and there is no link to an example file. I have tried several AASX files from https://admin-shell-io.com/samples/ but they fail with the UI message "Error! Server responded with: Error: Unexpected response format"

And from the container logs in aas-env:

```
ÄAAS EnvironmentÅ Äio-8081-exec-10Å o.e.d.a.v.d.aasx.AASXDeserializer        : AASX contains wrong Relationship namespace. This may be related to the AASX being created with an old version of AASX Package Explorer or an old version of AAS4J. Future compatibility with the wrong namespace may not be guaranteed
```

I have also searched the repos for any example file and found "a.aasx" in the [basyx-java-components repo](https://github.com/eclipse-basyx/basyx-java-components/tree/main/basyx.components/basyx.components.docker/basyx.components.AASServer/src/main/resources/aasx). However, it also fails with the message:

```
ÄAAS EnvironmentÅ Änio-8081-exec-3Å v.d.x.i.d.NoEntryWrapperListDeserializer : Found empty list item (e.g., '<preferredName />' of dataSpecificationIec61360) in XML. This is most likely an error.
````

Can someone provide a working `.aasx` example file? Or did I missed something? It might also be a good idea to put a file link or additional infos in the Quick Start Guide.

**Comment by aaronzi** [comment]
Hello @emareg,

we provide an .aasx file in our examples: https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/examples/BaSyxMinimal/aas

You can try this for now. If you need more shells for more specific examples (for example implementing standardized submodels), please write me a mail.

**Comment by emareg** [comment]
Thank you very much, these files work! I think it would be a good idea to provide this link in the Quick Start Guide where it says you should upload an AASX file :)

**Comment by aaronzi** [comment]
Good suggestion, I updated our wiki accordingly.
