### ISSUE TITLE
[BUG] Registration of newly uploaded AASes within registry not working for nginx setup  

### ISSUE THREAD

**Issue by barthchristian** [eclipse-basyx/basyx-java-server-sdk#409]
**Describe the bug**
I setup an basyx system, very similar to the BaSyxNGINX example https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/examples/BaSyxNGINX, just without discovery service. When trying to upload a new AAS, the server respons with the error message 400. However, the AAS is uploaded into the AAS repository, visible only when browsing directly to it. Within the registry, there is no entry, and thus also nothing is visible in the UI. The same shell worked for an older setup of basyx just without the nginx component. Same behaviour occurs for standard shells like maximal.json.

**To Reproduce**
1. Go to UI
2. Try to upload an AAS

**Expected behavior**
The AAS should be registered within the registry and sb-registry components.

**BaSyx (please complete the following information):**
- BaSyx Version  v2.0
- BaSyx SDK Java
- AAS Version  DotAAS V3

**Screenshots**
![image](https://github.com/user-attachments/assets/f52351d0-07a5-41f6-84c0-cec26a8dea48)

![image](https://github.com/user-attachments/assets/ab7d0ef4-0dcd-42f3-9721-15209e69054d)

![image](https://github.com/user-attachments/assets/4e6eac10-9c9b-4360-9b8e-92cc2597e179)

**Used Asset Administration files (.aasx/.json/.xml)**
Please drop your AAS files here that were used when the bug was encountered.

**BaSyx configuration**
Provide details about the configuration you used. If possible, attach the configuration as a .zip file.

**System (please complete the following information):**
 - OS: Linux on aws
 - CPU architecture:  x86
 - Browser firefox

**Additional context**

**Comment by aaronzi** [comment]
Hi @barthchristian,

I would assume that the problem lies in how the registry integration is configured.
Can you please share your .properties file for the AAS environment so that I can point you in the right direction?

**Comment by barthchristian** [comment]
Hi Aaron,

thanks for looking into this! Here is the aas-env.properties:
[aas-env_properties.txt](https://github.com/user-attachments/files/16846792/aas-env_properties.txt)

**Comment by barthchristian** [comment]
Hi Aaron,
anything suspicious with the aas-env file?
I tried several modifications, without success so far. The error still holds.
Cheers,
Christian

**Comment by barthchristian** [comment]
I tried with
server.servlet.context-path = /aas-env/ 
and now it seems to work.

**Comment by aaronzi** [comment]
Hi Christian, sorry for the late response. Great to hear that you were able to solve the problem. Depending on the nginx config the trailing "/" is needed.
