### ISSUE TITLE
[BUG] 1 Keycloak for two environments 

### ISSUE THREAD

**Issue by gerberm-at-msg** [eclipse-basyx/basyx-java-server-sdk#421]
**Describe the bug**
I have setup an AAS Network with all components lets say with IP address 192.168.178.76. RBAC etc works all fine:
![image](https://github.com/user-attachments/assets/ff60ede3-0fc4-4292-8178-9008dfb59934)

Now I have created a second AAS Network lets say with 192.168.178.77 with all components but without Keycloak. In the docker compose I have linked in the 77-network to the keyclaok of 76. 
![image](https://github.com/user-attachments/assets/29f5ca9c-9a43-4e70-9c25-843a125d73bd)

Based on the RBAC default config I have created a second client called "workstation-2" with the same settings as workstation-1, but a new client-secret. This is then provided in the aas-env.properties 

Anyway, when the setup has started, I cannot login because the Keycloak-Login-Mask tells me that the redirect_uri is invalid. 
![image](https://github.com/user-attachments/assets/2e51f07a-41c6-4433-bef4-6df4ae593369)

This is the uri that caused the error
```
http://192.168.178.76:9097/realms/BaSyx/protocol/openid-connect/auth?client_id=basyx-web-ui&redirect_uri=http%3A%2F%2F192.168.178.77%3A3000%2F&state=ab8d87ee-e95e-4935-8105-29b496938ddb&response_mode=fragment&response_type=code&scope=openid&nonce=3dc1ed30-76af-4a02-b4d0-9b3054503ad4&code_challenge=_Qvivuiv3nm91bFmAnL4gMkI0kOW0nalcJz3zwvLSqs&code_challenge_method=S256
```

**To Reproduce**
See above

**Expected behavior**
Login mask possible and redirect back to the 192.168.178.77 GUI

**BaSyx (please complete the following information):**
- BaSyx Version 2.0.0-milestone-03.1

**BaSyx configuration**
Provide details about the configuration you used. If possible, attach the configuration as a .zip file.

**System (please complete the following information):**
 - OS: Debian on Mac
 - CPU arm64 (M3)
 - Browser Edge, Chrome, Safari

Thx for you help

**Comment by aaronzi** [comment]
Hi @gerberm-at-msg,

this problem seems to be related to the configuration of Keycloak and not to BaSyx itself. I would suggest that you look for help on the Keycloak forums and their wikis.

If there is a bug in BaSyx itself, please feel free to reopen this issue and provide us with more details and logs of the BaSyx components.

Best regards,
Aaron
