### ISSUE TITLE
[Question] Endpoints /shells/{aasIdentifier} and /submodels/{submodelIdentifier} returns a different JSON format than /serialization

### ISSUE THREAD

**Issue by JS-Aibel** [eclipse-basyx/basyx-java-server-sdk#423]
**Describe the question**
Why does the endpoints `/shells/{aasIdentifier}` and `/submodels/{submodelIdentifier}` returns a different JSON format than the `/serialization` endpoint?

When using the  BaSyx-Python SDK method `read_aas_json_file()`, the json from the` /shells/` and the `/submodels/ `endpoint will not return any objects in the object store. When using the `/serialization` endpoint the method work as expected.

**BaSyx:**
- BaSyx Version [v2.0]
- BaSyx SDK [Python]
- AAS Version [DotAAS V3]

**Comment by aaronzi** [comment]
Hello @JS-Aibel,

is this a question for the BaSyx Python SDK or actually for the BaSyx Java SDK?
If it's for Python, please create an issue here: https://github.com/eclipse-basyx/basyx-python-sdk

For documentation on what an endpoint needs to return according to specification, please take a look here: https://app.swaggerhub.com/apis/Plattform_i40/Entire-API-Collection/V3.0.1

**Comment by JS-Aibel** [comment]
Thanks for answering, @aaronzi.

The question is ment for the basyx-java-server-sdk **AAS Environment**  and why the endpoints `/shells/{aasIdentifier}` and `/submodels/{submodelIdentifier}` returns a different JSON format than the `/serialization` endpoint?

The mention of BaSyx-Python SDK was only meant as a use case where the difference in response had an impact.
From your answer I assume you are only following the specification of the AAS Part 2: Application Programming Interfaces?

**Comment by aaronzi** [comment]
Yes, that's right. We follow the API specification for each of our endpoints. However, if you think we have made a mistake, we would be happy to hear about it.

I will close this issue as the original question has been answered. Feel free to open a new one if you think we have a bug in our implementation or have not followed the specification.
