### ISSUE TITLE
Incorrect properties file location binding

### ISSUE THREAD

**Issue by mhrimaz** [eclipse-basyx/basyx-java-server-sdk#43]
In all the [updated examples](https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/414a8ba55a854c824d98c764d8043790ba812af9/basyx.conceptdescriptionrepository/Readme.md) `/usr/share/config` has been used for binding the location of properties file.
This is for previous version of basyx. For basyx 2 [/application/application.properties](https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/414a8ba55a854c824d98c764d8043790ba812af9/examples/docker-compose.yml#L19C10-L19C65) is the source locaiton for reading properties.

**Comment by mhrimaz** [comment]
@jannisjung

**Comment by FrankSchnicke** [comment]
Thank you very much for pointing this out. The documentation update was missed during the initial PR.
