### ISSUE TITLE
[BUG] File Upload is not working

### ISSUE THREAD

**Issue by oliverbusch** [eclipse-basyx/basyx-java-server-sdk#433]
File Upload does not work

**To Reproduce**
1. Setup BaSyx (examples/BaSyxMinimal)
2. Open http://localhost:3000/
3. Select the first entry TestAssetAdministrationShell
4. Goto TestSubmodel/ExampleSubmodelE/ExampleSubmodelE
5. Upload a pdf file
6. See error

**Expected behavior**
File should be Upload does not work

**BaSyx (please complete the following information):
- BaSyx Version [v2.0] - Main Branch 04.09.2024

**Screenshots**
![image](https://github.com/user-attachments/assets/e43d0e6e-c7f2-4917-82e8-671338372a34)
![image](https://github.com/user-attachments/assets/e2f9118d-e757-4184-97bc-d5397e273885)

**System**
OS: [Docker on Linux]

**Comment by aaronzi** [comment]
Hi @oliverbusch,

I'm pretty sure the problem you are facing is related to the payload size (so the size of your PDF).
By default, the maximum payload size is 1MB. Your PDF is probably bigger than that. Could you please verify that? To solve the problem, you can add the following lines to the `aas-env.properties` file:

```
spring.servlet.multipart.max-file-size=128MB
spring.servlet.multipart.max-request-size=128MB
```

You can adapt the size to your needs.
Please inform us if this helped.

**Comment by oliverbusch** [comment]
Hi @aaronzi,
not that's not the case. I've tested it with the attached file
[Test-pdf_4.pdf](https://github.com/user-attachments/files/16893000/Test-pdf_4.pdf)

By the way, it is not possible to download a file. But that's another bug.

**Comment by FriedJannik** [comment]
Hi @oliverbusch 
I noticed that your UI tries to connect to KeyCloak.
If you had a secure BaSyx setup running before, there may be a caching problem in the UI.
Could you please try to reload the UI with Ctrl+F5 and try again?
It would be nice if you could let us know if this helps, thank you.

**Comment by oliverbusch** [comment]
Hi @aaronzi,
it looks like the UI wants to connect a KeyCloak. But I am using the examples/BaSyxMinimal configuration and have never installed any other configuration before.

**Comment by oliverbusch** [comment]
With the version from today (09:09:2024 13.20) it works again.
