### ISSUE TITLE
Configuration of MQTT auth/security

### ISSUE THREAD

**Issue by abhishekmaha23** [eclipse-basyx/basyx-java-server-sdk#44]
The MQTT configuration seems very minimal and does not support authentication or TLS.

**Comment by FrankSchnicke** [comment]
We're utilizing spring's **ConfigurationProperties** mechanism (cf. [MqttConfiguration.java](https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/main/basyx.submodelrepository/basyx.submodelrepository-feature-mqtt/src/main/java/org/eclipse/digitaltwin/basyx/submodelrepository/feature/mqtt/MqttConfiguration.java)). Thus, you can set every parameter of MqttConnectOptions for which a setter exists (cf. [MqttConnectOptions](https://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttConnectOptions.html)) via mqtt.$propertyName.

**Comment by abhishekmaha23** [comment]
Was able to make a connection, thanks!
