### ISSUE TITLE
[Question] How can Package Explorer connect to AAS Environment?

### ISSUE THREAD

**Issue by JS-Aibel** [eclipse-basyx/basyx-java-server-sdk#440]
**Describe the question**

The [Package Explorer](https://github.com/eclipse-aaspe/package-explorer) has the following features. 
- GET Submodel from url
- PUT Submodel from url
- Serve AAS as Rest
- AASX file repository

Can any of these features interface with the [AAS Environment — Eclipse BaSyx™](https://wiki.basyx.org/en/latest/content/user_documentation/basyx_components/v2/aas_environment/index.html)?

**BaSyx:**
BaSyx Version [v2.0]
AAS Version [DotAAS V3]

**Comment by aaronzi** [comment]
Hi @JS-Aibel,

in general yes but I don't think that this feature even works in the Package Explorer no matter what service you are trying to connect to. I tried the [newest release of the Package Explorer](https://github.com/eclipse-aaspe/package-explorer/releases/tag/v2024-06-10.alpha) and it didn't do anything after providing the URL to a submodel hosted via BaSyx. Not even an error message.

**Comment by JS-Aibel** [comment]
Thanks for checking it out, @aaronzi 
I did not get it to work in Package Explorer either. Since basyx-java-server-sdk is following the SpecificationAssetAdministrationShell_Part2_API, I guess the error must be in the Package Explorer?

**Comment by aaronzi** [comment]
Yes, that's also what I thought.
