### ISSUE TITLE
[BUG] MongoDB hello command not supported by Azure CosmosDB for MongoDB

### ISSUE THREAD

**Issue by mm-mse** [eclipse-basyx/basyx-java-server-sdk#452]
**Describe the bug**
The BaSyx components throw an `CommandNotSupported` exception for the `hello` command when using an Azure CosmosDB for MongoDB as a storage. The Azure CosmosDB version is 7.0. 

**To Reproduce**
1. Deploy container based on e.g. `eclipsebasyx/aas-registry-log-mongodb:2.0.0-milestone-04` with Azure CosmosDB for MongoDB configured as MongoDB.
1. See error

**Expected behavior**
No exception gets thrown.  

**BaSyx (please complete the following information):**
- BaSyx Version  v2.0
- BaSyx SDKJava
- AAS Version DotAAS V3

**Screenshots**

**Used Asset Administration files (.aasx/.json/.xml)**
Please drop your AAS files here that were used when the bug was encountered.

**BaSyx configuration**
Provide details about the configuration you used. If possible, attach the configuration as a .zip file.

**System (please complete the following information):**
 - OS: Linux, docker
 - CPU architecture: x86

**Additional context**
I guess it's more a problem of the CosmosDB because it is not feature complete with the official MongoDB. However a compatibility with the Azure CosmosDB would be great. The `ping` command could be an alternative depending on the usecase for the `hello` command. The interesting part of the logs looks as follows:
```java
Caused by: com.mongodb.MongoCommandException: Command failed with error 115 (CommandNotSupported): 'Command hello not supported.' on server <servername>.mongo.cosmos.azure.com:10255. The full response is {"ok": 0.0, "errmsg": "Command hello not supported.", "code": 115, "codeName": "CommandNotSupported"}
```

**Comment by aaronzi** [comment]
Hello @mm-mse,

since CosmosDB is currently not in the scope of BaSyx Java V2 and the problem is most likely not caused by BaSyx itself, we will not try to solve the issue. But if you want, you can implement a feature for CosmosDB as a storage backend. BaSyx Java is very extensible in this respect.
