### ISSUE TITLE
[BUG] Databridge Container not linux/arm64/v8 compatible

### ISSUE THREAD

**Issue by gerberm-at-msg** [eclipse-basyx/basyx-java-server-sdk#453]
**Describe the bug**
As with the dashboard-api the databridge is also not compatible with the linux/arm64/v8 (Mac M* Chip) but is needed to get the databridge running. Can you please help me with it and provide a compatible container for it too

```databridge:
    image: eclipsebasyx/databridge:1.0.0-SNAPSHOT
    container_name: databridge-mqtt
    volumes:
      - "./databridgeConfig:/usr/share/config"
    restart: always
```

``` 
! databridge The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                                 0.0s
```

**Comment by aaronzi** [comment]
Hello @gerberm-at-msg,

we will check if this is possible for the current setup of the databridge and update the image on dockerhub if it is.

**Comment by aaronzi** [comment]
Hello @gerberm-at-msg,

we updated the DataBridge to support arm/v8 as well. The image tag for the new version is `eclipsebasyx/databridge:1.0.0-milestone-08`.

**Comment by gerberm-at-msg** [comment]
Hi @aaronzi 
sorry I was away until today. Thank you!
I tested it and can confirm that it works.
