### ISSUE TITLE
[BUG] Submodel Service: The Call of GetSubmodelMeta Changes The InMemory Storage Object

### ISSUE THREAD

**Issue by geso02** [eclipse-basyx/basyx-java-server-sdk#459]
**Describe the bug**

When reading the metadata of the submodel-service submodel, the in-memory object is changed by [setting the list of all submodel elements to null](https://github.com/eclipse-basyx/basyx-java-server-sdk/blob/main/basyx.submodelservice/basyx.submodelservice-http/src/main/java/org/eclipse/digitaltwin/basyx/submodelservice/http/SubmodelServiceHTTPApiController.java#L168).

Subsequent calls then throw an exception. Besides, the object should not be changed during the reading operation. You would rather need to copy the data except for the submodel elements.
```
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "allSubmodels" is null
```

**To Reproduce**
1. Set up the submodel  service
2. GET /submodel/$metadata
3. GET /submodel/submodel-elements 
=>Exception occurs:
  {
    "timestamp": 1726556325622,
    "status": 500,
    "error": "Internal Server Error",
    "path": "/submodel/submodel-elements"
  }

**Expected behavior**

We should rather copy the object - at least for the in-memory solution - but not alter the object on a GET-operation.

**BaSyx (please complete the following information):**
- BaSyx Version [v2.0]
- BaSyx SDK [Java]
- AAS Version [DotAAS V3]

**System (please complete the following information):**
 - OS: [Docker on Windows]
 - CPU architecture: [x86]

**Comment by aaronzi** [comment]
Hi @geso02,

thank you for reporting this! We will have a look and come up with a fix.
