### ISSUE TITLE
[BUG] AAS GUI - ExternalReference same as ModelReference - Only Refers to provided SMR

### ISSUE THREAD

**Issue by gerberm-at-msg** [eclipse-basyx/basyx-java-server-sdk#461]
**Describe the bug**
Startingpoint: 
I have two separate AAS-Environments in two IP-Areas, both of them have an own AAS and SubModel Registry (SMR). I like to reference to a Submodule in the other ASS-Environment. Therefore I need to use reference to a different Submodelregistry as the provided SMR in the UI. For this I use instead of ModelReference, ExternalReference. However, there is no functional difference in the UI for it. 

This is the expectation. 
Instead of using the ID (in the URI format) I use the entire Submodel-Reference with the SM-Registry Service. 
```
{
  "assetAdministrationShells": [
    {
      "idShort": "VerlinktesSubmodul",
      "id": "https://msg.group/aas/sm/8583_3140_7032_9766",
      "assetInformation": {
        "assetKind": "Instance"
      },
      "submodels": [
        {
          "type": "ExternalReference",
          "keys": [
            {
              "type": "Submodel",
              "value": "http://192.168.178.77:8081/submodels/aHR0cHM6Ly9tc2cuZ3JvdXAvYWFzL3NtLzY1MjJfMjE3MV85MDQyXzEyMjE"
            }
          ]
        }
      ],
      "modelType": "AssetAdministrationShell"
    }
  ],
  "submodels": [ ]
}
```

This is how it currently works to reference to the local SM-Registry. The value of keys is base64 decoded as ID and the UI creates the link to the submodel as taken from config. 
```
{
  "assetAdministrationShells": [
    {
      "idShort": "VerlinktesSubmodul",
      "id": "https://msg.group/aas/sm/8583_3140_7032_9766",
      "assetInformation": {
        "assetKind": "Instance"
      },
      "submodels": [
        {
          "type": "ModelReference",
          "keys": [
            {
              "type": "Submodel",
              "value": "https://msg.group/aas/sm/6522_2171_9042_1221"
            }
          ]
        }
      ],
      "modelType": "AssetAdministrationShell"
    }
  ],
  "submodels": [
  ]
}
```
Problem is here, that the change of type ModelReference and External Reference does not make a difference. If I use ExternalReference in the second example it only works with the same value (the ID) not the entire URL with a different SMR.

**Comment by mhrimaz** [comment]
@gerberm-at-msg according to the metamodel you cannot have a ExternalReference with Submodel as the first key. You should have a GlobalReference when you are using ExternalReference https://aas-core-works.github.io/aas-core-meta/v3/AssetAdministrationShell.html#submodels.
Moreover, the AssetAdministrationShell should only contain ModelReference to Submodel.

So what you are doing is against the constraints of metamodel. See https://aas-core-works.github.io/aas-core-meta/v3/AssetAdministrationShell.html#submodels and the last listed invariant.

**Comment by gerberm-at-msg** [comment]
Hi @mhrimaz, 
thank you for the quick response, really appreciate it. 

Regarding. GlobalReference. As far as I understood the GlobalReference has been replaced with ExternalReference this year in June in the Metamodel IDTA Number: 01001-3-0-1. I guess in BaSyx GUI it is considered already since it throws an error using GlobalReference but not for ExternalReference or ModelReference. 
 
So how do I Reference a submodule instead in a different Infrastructure instead? Having decentralised digital twins is the key argument of using AAS, but not be able to reference them makes them just copies and therefore useless.

**Comment by mhrimaz** [comment]
@gerberm-at-msg I don't know what you are referring. But 01001-3-0-1 is just the metamodel part one:

![image](https://github.com/user-attachments/assets/19c1fcaf-b83b-4e4a-bd4c-9d8465f94d45)

ExternalReference should contain GlobalReference as first key:

![image](https://github.com/user-attachments/assets/e318be8c-aa5b-4e04-acb6-a26367a7ce91)

AssetAdministraionShell should only contain ModelReference and only ModelReference to Submodel:
![image](https://github.com/user-attachments/assets/9c0bceab-575b-433d-ad0a-636de7c804f7)


So Back to your point:

> So how do I Reference a submodule instead in a different Infrastructure instead? Having decentralised digital twins is the key argument of using AAS, but not be able to reference them makes them just copies and therefore useless.

You just put the ID of submodel. the UI or whatever application should query the registry and pass the ID to the registry and get the location. 

![image](https://github.com/user-attachments/assets/d6d9ab8e-8c27-4ee9-97c9-ac53fa12b015)

Now the question is which registry to query? You can start with a list of known registries and query them (all of them, inefficiently) and be hopeful that those registries know the place of your submodel id. Or you can rely on your submodel id, assume that the submodel id might indicate the location of registry (https://github.com/eclipse-basyx/basyx-java-server-sdk/pull/313). So this is somewhere that metamodel lacks. Either you need assumptions to make which is not interoperable, or make the registry a centralized component. If you found the answer or think i am wrong, let me know.

**Comment by gerberm-at-msg** [comment]
Thank you for your extensive explanation. I trust you with your response, still trying to fully comprehend everything. Not sure If I like the solution though. Is it possible to have a quick call to just clarify questions on a short route.

**Comment by aaronzi** [comment]
Thank you @mhrimaz for the very good explanation. You are absolutely right. Finding the right registry can be a challenge in a highly distributed system. The hierarchical registries feature can be a solution to that problem. Currently, the UI is designed to work with exactly one AAS and Submodel registry. The idea is to have multiple UIs running (or multiple tabs in the browser) when visualizing Shells from multiple registries of the same kind. A registry would be a view on a set of shells. A Shell could potentially be registered in one registry or multiple ones. The only important thing is that the UI is able to follow the path defined by the specification shown in Figure 3.
