### ISSUE TITLE
DataBridge in this version

### ISSUE THREAD

**Issue by AnVentura** [eclipse-basyx/basyx-java-server-sdk#483]
Good evening, I'm trying to use Basyx Databridge in this version, is that possible?

I wanted to do a simple example of intercepting an endpoint and changing its content, I thought of doing a GET on localhost:8081/shells, and changing for example to a 'Hello Word' just to make sure the DataBridge is working.

For that i am using this docker compose

![imagem](https://github.com/user-attachments/assets/410b89d2-5fa2-4e06-bf2d-ec709ff47dc9)

And i am also using on the directory data-bridge
httpconsumer.json
![imagem](https://github.com/user-attachments/assets/c90c6a92-64d7-4fa6-a9c4-d3c002b10142)

jsonatatransformer.json
![imagem](https://github.com/user-attachments/assets/89c84785-2ff9-4243-bf25-f2c66135b16e)

routes.json
![imagem](https://github.com/user-attachments/assets/1fa4fa39-9c4c-44d2-baed-5a81ab88fe0b)

testTransformer.jsonata
![imagem](https://github.com/user-attachments/assets/116027f7-677b-495e-952d-af8f102dc5ee)

I hope you can help me.

**Comment by aaronzi** [comment]
Hello @AnVentura,

yes, the Databridge is compatible with BaSyx V2 and the AAS Environment.
You can find an example on how to configure it here: https://github.com/eclipse-basyx/basyx-databridge/tree/main/databridge.examples/databridge.examples.dot-aas-v3-api/src/main/resources

This example is setup for mqtt but the important part for you would be the aasserver.json config file. There you can see that the additional parameter `api` is being set:

```json
[
	{
		"uniqueId": "ConnectedTestSubmodel/DotAASV3ConformantApiProperty",
		"submodelEndpoint": "http://localhost:4001/submodels/c3VibW9kZWxJZA==",
		"idShortPath": "DotAASV3ConformantApiSMC.DotAASV3ConformantApiProperty",
		"api": "DotAAS-V3"
	},
	{
		"uniqueId": "ConnectedTestSubmodel/DotAASV3ConformantApiStringProperty",
		"submodelEndpoint": "http://localhost:4001/submodels/c3VibW9kZWxJZA==",
		"idShortPath": "DotAASV3ConformantApiSMC.DotAASV3ConformantApiStringProperty",
		"api": "DotAAS-V3"
	}
]
```

Hope this helps. If you have further questions, please attach your entire setup as .zip file so that we can try out your example to help you fix it.

**Comment by AnVentura** [comment]
Hello @aaronzi,
Thanks for your answer, I was able to do it, I just had to change the image of my databridge to a newer version.
I have more questions, I used the databridge to change the values inside my AAS, what else i can use the databridge for?

Look forward to hearing from you

**Comment by aaronzi** [comment]
Hi @AnVentura,

there are some use cases the Databridge is very helpful for:

1. Use it the other way around to update values in the asset based on changes in the AAS (for example possible with MQTT; see [here](https://github.com/eclipse-basyx/basyx-databridge/tree/main/databridge.examples/databridge.examples.dot-aas-v3-jsonata-mqtt/src/main/resources))
2. Apply transformations to the data that is transmitted (see for example [here](https://github.com/eclipse-basyx/basyx-databridge/tree/main/databridge.examples/databridge.examples.opcua-jackson-jsonata-aas/src/main/resources))
3. Use basic authentication for secured communication (see [here](https://github.com/eclipse-basyx/basyx-databridge/tree/main/databridge.examples/databridge.examples.httppolling-auth-jsonata-aas/src/main/resources))
4. Use the multicast feature to connect one source to multiple sinks (full example [here](https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/examples/BaSyxDatabridge))
5. Try out other protocols (see [all examples](https://github.com/eclipse-basyx/basyx-databridge/tree/main/databridge.examples))

**Comment by AnVentura** [comment]
I am already using some of those examples, but my question is: Instead of using databridge to change values inside de AAS, can i use the databridge to send information of my AAS? For example to a DataSpace connector (EDC)?

**Comment by aaronzi** [comment]
Yes, as described in 1. you can send data from the AAS to somewhere else. The EDC is currently not a use case for the databridge. Connectivity to dataspaces using the EDC will come to BaSyx itself. This is currently in it's planning phase.

**Comment by AnVentura** [comment]
I tried what is described in 1, but i wasn't able to get the data from my submodel

![imagem](https://github.com/user-attachments/assets/07e74bdc-9e10-43f2-b05a-edbc407ddbe3)

The first part is to access the data, and change the value, and the next one is to get all the data inside de submodel

**Comment by aaronzi** [comment]
The routes configuration you shared as screenshot looks off. When you want to transfer Data from a Submodel to a MQTT topic the datasource would be the Submodel and the MQTT topic the datasink.

**Comment by AnVentura** [comment]
@aaronzi Can you help me please?
I switched and still this is the error
![imagem](https://github.com/user-attachments/assets/a0da8c99-7f75-4594-a364-acc9cab82e70)

This is my route 
![imagem](https://github.com/user-attachments/assets/4f8eac5d-deba-48ca-80c3-542129a53e4f)


This is datasource configuration, submodelEnpoint is "" because i want all the whole submodel
![imagem](https://github.com/user-attachments/assets/5cad7ea4-e9e1-4fca-818b-d17f267c55c6)

And this is my mqtt
![imagem](https://github.com/user-attachments/assets/94d6fc61-ee3b-49d7-a2ff-774d74a4f468)

**Comment by aaronzi** [comment]
Are you using the same naming scheme of the files as in this example?: https://github.com/eclipse-basyx/basyx-databridge/tree/main/databridge.examples/databridge.examples.aas-jsonata-mqtt/src/main/resources

**Comment by AnVentura** [comment]
No, i am using the name of another example; the names that i have is assserver.json, jsonatatransformer.json, mqttconsumer.json, routes.json and timerconsumer.json

**Comment by aaronzi** [comment]
Can you send your entire setup as a zip file then so that we can try it ourselves and find potential errors in the config?
