### ISSUE TITLE
[QUESTION] Is keycloak the only available jwtBearerTokenProvider? 

### ISSUE THREAD

**Issue by mmaeffert** [eclipse-basyx/basyx-java-server-sdk#508]
I tried to use another TokenProvider which also uses OAuth2. However, the token structure might differ and I can not find the option to set an openId-Connect configuration path. 
Is Keycloak the only available option?

**Comment by mdanish98** [comment]
Hi @mmaeffert ,
Thanks for your question.
Yes, currently Keycloak is the only available option in BaSyx.
