### ISSUE TITLE
AAS Environment component MQTT conflicting beans

### ISSUE THREAD

**Issue by FlorianWege-IESE** [eclipse-basyx/basyx-java-server-sdk#55]
When starting up the AAS Environment component from code and enabling mqtt for different sub components, there appears to be a `ConflictingBeanDefinitionException` because the `MqttConfiguration` classes of the sub components share the same simple name.

application.properties:
```
basyx.aasrepository.feature.mqtt.enabled = true
basyx.submodelrepository.feature.mqtt.enabled = true
mqtt.clientId=TestClient
mqtt.hostname = localhost
mqtt.port = 1883
```

or

```
basyx.feature.mqtt.enabled = true
mqtt.clientId=TestClient
mqtt.hostname = localhost
mqtt.port = 1883
```

`Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'mqttConfiguration' for bean class [org.eclipse.digitaltwin.basyx.submodelrepository.feature.mqtt.MqttConfiguration] conflicts with existing, non-compatible bean definition of same name and class [org.eclipse.digitaltwin.basyx.aasrepository.feature.mqtt.MqttConfiguration]`

So you currently have to target a specific bean like only `basyx.aasrepository.feature.mqtt.enabled = true`. The different MQTTConfigurations look the same exception for the bean condition. If they should be idempotent, it could be extracted and reused I guess but maybe one could want to have different mqtt parametrizations per sub component. All of the sub components currently seem to be using `mqtt.clientId` for instance without the AAS Environment putting the different configuration properties into context.

**Comment by FrankSchnicke** [comment]
Thank you very much for pointing this out. We will take a look at it and fix it in the coming weeks.
