### ISSUE TITLE
Containers not working with 'Azure Cosmos DB for MongoDB'

### ISSUE THREAD

**Issue by mm-mse** [eclipse-basyx/basyx-java-server-sdk#62]
The current published Docker containers can't operate with "Azure Cosmos DB for MongoDB" as MongoDB backend. The logs show the error  `Command failed with error 115 (CommandNotSupported): ''text' is not supported' on server <Azure Cosmos DB for MongoDB name>. The full response is {"ok": 0.0, "errmsg": "'text' is not supported", "code": 115, "codeName": "CommandNotSupported"};`

The reason seems to be on the site of Azure. The current version 4.2 of the Cosmos DB does not support all MongoDB features ([Microsoft Documentation](https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/feature-support-42)). However it might be desireable for BaSyx users to be able to use this Azure Resource.

**Comment by FrankSchnicke** [comment]
Thank you very much for pointing this out. We are aware of this issue - Azure Cosmos DB does not support text based indexing which we are using at the moment. We will look for alternatives and update the images.

**Comment by FrankSchnicke** [comment]
The fix was merged and the SNAPSHOT images were updated.

**Comment by mm-mse** [comment]
The new Docker images did not work for me. I set up a Azure Cosmos DB for Mongo DB and tried to connect a submodel repository and an aas repository. Both fail, the logs are attached. 

docker-compose:
```networks:
  basyx:
    internal: false

services:
  submodel-repo:
    container_name: submodel-repo
    image: eclipsebasyx/submodel-repository:2.0.0-SNAPSHOT
    environment:
      BASYX_BACKEND: MongoDB
      SPRING_DATA_MONGODB_DATABASE: submodels     
      SPRING_DATA_MONGODB_URI: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/?tls=true
    ports:
      - 8081:8081
    networks:
      - basyx

  aas-repo:
    container_name: aas-repo  
    image: eclipsebasyx/aas-repository:2.0.0-SNAPSHOT
    ports:
      - 8082:8081
    environment:
      BASYX_BACKEND: MongoDB
      SPRING_DATA_MONGODB_DATABASE: shells     
      SPRING_DATA_MONGODB_URI: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/?tls=true
    networks:
      - basyx
```

[aas-repo.log](https://github.com/eclipse-basyx/basyx-java-server-sdk/files/12519687/aas-repo.log)
[submodel-repo.log](https://github.com/eclipse-basyx/basyx-java-server-sdk/files/12519688/submodel-repo.log)

**Comment by FrankSchnicke** [comment]
Unfortunately CosmosDB is again handling something differently than MongoDB. This issue was already reported in a separate ticket, see https://github.com/eclipse-basyx/basyx-java-server-sdk/issues/80

**Comment by mm-mse** [comment]
Thanks for the quick answer and pointing that out. For the AAS Repo I am having the same issue as in the other ticket but the submodel repo does not even connect to Azure Cosmos DB. There seems to be another issue:

`The bean 'getSubmodelServiceFactory', defined in class path resource [org/eclipse/digitaltwin/basyx/submodelrepository/MongoDBSubmodelRepositoryConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/eclipse/digitaltwin/basyx/submodelrepository/component/SubmodelRepositoryConfiguration.class] and overriding is disabled.`

**Comment by mhrimaz** [comment]
@mm-mse Are you trying to run directly the code form IDE or you are using the Docker? Is your docker image updated?
I haven't tested it with the docker, but I can run the code directly without any issue.

Regarding Azure Cosmos DB compatibility issue, follow the other issue. #80

**Comment by FrankSchnicke** [comment]
> Thanks for the quick answer and pointing that out. For the AAS Repo I am having the same issue as in the other ticket but the submodel repo does not even connect to Azure Cosmos DB. There seems to be another issue:
> 
> `The bean 'getSubmodelServiceFactory', defined in class path resource [org/eclipse/digitaltwin/basyx/submodelrepository/MongoDBSubmodelRepositoryConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/eclipse/digitaltwin/basyx/submodelrepository/component/SubmodelRepositoryConfiguration.class] and overriding is disabled.`

This was fixed in PR https://github.com/eclipse-basyx/basyx-java-server-sdk/pull/82. However, we did not push a new snapshot version until now. This will happen at the end of this week.

**Comment by mm-mse** [comment]
alright, thanks
