### ISSUE TITLE
AAS Environment is not implementing the "Self-Description" interface

### ISSUE THREAD

**Issue by in-fke** [eclipse-basyx/basyx-java-server-sdk#64]
After running AAS environment, this works
`curl http://localhost:8081/shells`
but this does not:
`curl http://localhost:8081/description`
consistently, internal OpenAPI (Swagger) does not state that this interface would be available,
yet it should be available according to spec?

**Comment by FrankSchnicke** [comment]
BaSyx Java V2 is not supporting all endpoints as of today. For example, the description endpoint is missing. However, it will be added in future.

**Comment by FrankSchnicke** [comment]
The description endpoint was added with https://github.com/eclipse-basyx/basyx-java-server-sdk/pull/94. However, due to ongoing discussions there may be some changes in future.
