### ISSUE TITLE
MongoDBAasRepository automatically creates AssetAdministrationShell.id, InMemoryAasRepository does not

### ISSUE THREAD

**Issue by in-fke** [eclipse-basyx/basyx-java-server-sdk#68]
MongoDBAasRepository (well, MongoDB, actually) automatically creates AssetAdministrationShell.id if null is passed for `createAas()`
**Is this is bug or a feature?**

If it's a feature, InMemoryAasRepository should also generate an id.

Currently InMemoryAasRepository allows to create a Shell with null id, and then throws CollidingIdentifierException if a second shell with id null is to be created. So it should either check for null / empty or generate one if null id given.

**Comment by FrankSchnicke** [comment]
Thanks for pointing this out, this is a bug. I will update this issue when the bug is fixed.

**Comment by FrankSchnicke** [comment]
Fixed by https://github.com/eclipse-basyx/basyx-java-server-sdk/pull/156
