### ISSUE TITLE
Does BaSyx Java V2 support the Submodel Element List in the AAS specification 3.0RC02?

### ISSUE THREAD

**Issue by nqduy35** [eclipse-basyx/basyx-java-server-sdk#97]
As in the README: "BaSyx Java V2 is fully compliant with Specification of the Asset Administration Shell Version 3...", so I suppose that BaSyx Java V2 is compliant with the latest version (3.0RC02) of the AAS specification. Then, it also supports Submodel Element List. Could you confirm that?

**Comment by aaronzi** [comment]
I am currently working on that for the AAS Web UI update. Can confirm that the SubmodelElementList is supported

![image](https://github.com/eclipse-basyx/basyx-java-server-sdk/assets/17433117/5787b445-cea4-4d15-80b4-871d0de3510c)

**Comment by FrankSchnicke** [comment]
Thanks @aaronzi for answering this question.
@nqduy35: V3RC02 is not the latest version. V3.0.0 for metamodell and V3.0.1 for API are the latest releases.
