### ISSUE TITLE
AAS Environment not supporting update of existing SubmodelElements

### ISSUE THREAD

**Issue by aaronzi** [eclipse-basyx/basyx-java-server-sdk#98]
According to the IDTA specification (DotAAS V3) it should be possible to update existing SubmodelElements as seen here: https://app.swaggerhub.com/apis/Plattform_i40/Entire-API-Collection/V3.0#/Submodel%20API/PutSubmodelElementByPath

It seems like this is not supported by BaSyx V2. Is this coming in the future?

**Comment by FrankSchnicke** [comment]
We will support this in future. As of today, the endpoints listed [here](https://github.com/eclipse-basyx/basyx-java-server-sdk/tree/main/basyx.submodelrepository) are supported. This includes the /$value endpoint, allowing SubmodelElement value update.

**Comment by aaronzi** [comment]
Thank you @FrankSchnicke. I think this is a very useful endpoint for editing AASs in BaSyx without the need to use for example the AASX Package Explorer. When the BaSyx Java Server SDK supports this, the AAS Web UI will get an update in the future to create and edit shells.

**Comment by FrankSchnicke** [comment]
Closed with linked PR.
